### ISSUE TITLE
非预期错误，shadowsocks将退出

### ISSUE THREAD

**Issue by bobchow** [shadowsocks/shadowsocks-windows#1071]
### Version(release version or AppVeyor link)
3.4.3

### Environment(Operating system, .NET Framework, etc)
windows 7 SP1
.NET Framework 4.6.2

### Steps you have tried
安装.NET Framework 4.6.2后，直接点击shadowsocks，然后报错

### Config and error log in detail (with all sensitive info masked)
[2017-03-10 14:31:27] [E] System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. 句柄无效。 (Exception from HRESULT: 0x80070006 (E_HANDLE))
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' ---> System.IO.FileLoadException: Could not load file or assembly '526336 bytes loaded from Shadowsocks, Version=3.4.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. 句柄无效。 (Exception from HRESULT: 0x80070006 (E_HANDLE))
File name: '526336 bytes loaded from Shadowsocks, Version=3.4.3.0, Culture=neutral, PublicKeyToken=null' ---> System.Runtime.InteropServices.COMException (0x80070006): 句柄无效。 (Exception from HRESULT: 0x80070006 (E_HANDLE))
   at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, SecurityContextSource securityContextSource)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly)
   at Costura.AssemblyLoader.ReadFromEmbeddedResources(Dictionary`2 assemblyNames, Dictionary`2 symbolNames, AssemblyName requestedAssemblyName)
   at Costura.AssemblyLoader.ResolveAssembly(String assemblyName)
   at Costura.AssemblyLoader.<Attach>b__0(Object s, ResolveEventArgs e)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

   at Shadowsocks.Model.Configuration.Load()
   at Shadowsocks.Controller.ShadowsocksController..ctor()
   at Shadowsocks.Program.Main()

**Comment by celeron533** [comment]
似乎是因为读取`gui-config.json`并请求`Newtonsoft.Json`解析的时候出现了问题。
你装完.Net framework后有没有重新启动过呢？

**Comment by bobchow** [comment]
有重启

**Comment by vkings1** [comment]
Nice!! Let me try this new version..

**Comment by wongsyrone** [comment]
Newtonsoft.Json应该是经过Fody.Costura嵌入进去了，检查下载的文件是不是有问题

**Comment by bobchow** [comment]
应该没有吧，从https://github.com/shadowsocks/shadowsocks-windows/releases/download/3.4.3/Shadowsocks-3.4.3.zip这里下载的，地址有问题吗？

**Comment by ssdemajia** [comment]
用管理员权限登录就行，是不是没有权限创建config文件
