### ISSUE TITLE
V401 fails in Windows 10 while v343 works well

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-windows#1124]
v343 worked well but v401 failed to connect
server version ss-libev v 3.0.5

### Version(release version or AppVeyor link)
4.0.1

### Environment(Operating system, .NET Framework, etc)
Windows 10 1607.

### Steps you have tried
1. restart, 2. clean all configure files

### What did you expect to see?
401 should work as 343
343 works well but 401 fails

### What did you see instead?
chrome failed to connect to websites

### Config and error log in detail (with all sensitive info masked)

[2017-04-20 17:29:20] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.CopyTo(Array array, Int32 index)
   at Shadowsocks.Encryption.Stream.StreamEncryptor.LegacyDeriveKey(Byte[] password, Byte[] key)
   at Shadowsocks.Encryption.Stream.StreamEncryptor.InitKey(String password)
   at Shadowsocks.Encryption.Stream.StreamEncryptor..ctor(String method, String password)
   at Shadowsocks.Encryption.Stream.StreamMbedTLSEncryptor..ctor(String method, String password)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   at Shadowsocks.Controller.TCPHandler.CreateRemote()
   at Shadowsocks.Controller.TCPHandler.StartConnect()

**Comment by wongsyrone** [comment]
Please provide more detail on how to reproduce, including your config.

**Comment by GitatHub** [comment]
Details:
1. download 401 and replace 343 with the new exe
2. run
3. failed
4. chrome said:
This site can’t be reached
The connection was reset.
Try:
Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_RESET

5. configure:
{
  "configs": [
    {
      "server": "IP.IP.IP.IP",
      "server_port": 114,
      "password": "PASS",
      "method": "aes-192-cfb",
      "remarks": "TAG1",
      "auth": false,
      "timeout": 5
    },
    {
      "server": "IP.IP.IP.IP",
      "server_port": 114,
      "password": "PASS",
      "method": "aes-192-cfb",
      "remarks": "TAG2",
      "auth": false,
      "timeout": 5
    },
    {
      "server": "IP.IP.IP.IP",
      "server_port": 114,
      "password": "PASS",
      "method": "aes-192-cfb",
      "remarks": "TAG3",
      "auth": false,
      "timeout": 5
    }
  ],
  "strategy": "com.shadowsocks.strategy.balancing",
  "index": -1,
  "global": false,
  "enabled": true,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 2008,
  "pacUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": false,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": ""
  }
}

6. Now I am using 343 and it is working well.
7. again, the server is on libev 305 (the latest version that has abandoned OTA)

@wongsyrone 

configre:

**Comment by wongsyrone** [comment]
What's the length of your password?

**Comment by GitatHub** [comment]
@wongsyrone  13 ~ 14 chars with # @ $ etc special chars

**Comment by wongsyrone** [comment]
Just make sure I'm using the same config to reproduce.

**Comment by wongsyrone** [comment]
try https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows/build/1.0.265/job/7jpnhmou1smtg3s7/artifacts

**Comment by GitatHub** [comment]
it's now working
thanks for your efforts.

**Comment by wongsyrone** [comment]
Done in 3b3a8c9077cdb97335d7b340ac0a7cfe27932c60
