### ISSUE TITLE
错误反馈：错误信息 Shdowsocks not-UI Error

### ISSUE THREAD

**Issue by jeopsh** [shadowsocks/shadowsocks-windows#1178]
### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
Windows 10 14393.1168

### Steps you have tried
重新打开应用

### What did you expect to see?
程序正常运行，没有错误信息

### What did you see instead?
显示错误信息

### Config and error log in detail (with all sensitive info masked)

```
 [E] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   at Shadowsocks.Program.Main()
```

**Comment by wongsyrone** [comment]
详细描述步骤并用这个debug版本，将错误日志发出来

https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-yqdou/build/1.0.32/job/ry0ujp4cofldnuen/artifacts

**Comment by jeopsh** [comment]
谢谢，问题已解决，原因未知。
删除了旧程序，重新下载了 Shadowsocks 后正常运行。
可能是因为电脑蓝屏原因导致文件损坏而致，我的电脑老旧，经常有蓝屏发生，也有蓝屏损坏文件的黑历史。

**Comment by celeron533** [comment]
请关闭SS，删除同文件夹下的`user-wininet.json`后，重试运行

**Comment by webbbbb** [comment]
Shadowsocks-4.0.6 无法解析二维码

**Comment by chenshaoju** [comment]
@webbbbb 此问题已知。

**Comment by Shaofanl** [comment]
win10更新后4.0.9无法启动
已尝试删除其它文件
.NET为4.7版本

log如下
```
[2018-05-07 03:34:40] System.Net.Sockets.SocketException (0x80004005): The procedure call table is invalid
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.TcpListener..ctor(IPAddress localaddr, Int32 port)
   at Shadowsocks.Controller.PrivoxyRunner.GetFreePort()
[2018-05-07 03:34:40] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.Listener.Start(Configuration config)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
[2018-05-07 03:35:15] System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_MainWindowHandle()
   at System.Diagnostics.Process.CloseMainWindow()
   at Shadowsocks.Controller.PrivoxyRunner.KillProcess(Process p)
[2018-05-07 03:35:15] System.Net.Sockets.SocketException (0x80004005): The procedure call table is invalid
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.TcpListener..ctor(IPAddress localaddr, Int32 port)
   at Shadowsocks.Controller.PrivoxyRunner.GetFreePort()
[2018-05-07 03:35:15] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.Listener.Start(Configuration config)
   at Shadowsocks.Controller.ShadowsocksController.Reload()

```

**Comment by chenshaoju** [comment]
```
System.Net.Sockets.SocketException (0x80004005): The procedure call table is invalid
```
感觉是Winsock或TCP/IP协议有问题。
请尝试一管理员身份启动命令提示符或PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一回车，三行执行完毕后重新启动计算机看看。

**Comment by chenshaoju** [comment]
该问题及有可能是Windows 10系统本身的问题导致的，这些莫名其妙的现象已经不是第一次出现了。
