### ISSUE TITLE
Launching Failed, alerting null reference

### ISSUE THREAD

**Issue by Antisunny** [shadowsocks/shadowsocks-windows#1200]
### Version 

`4.0.4`

### Environment(Operating system, .NET Framework, etc)

`Windows 10`
`.Net 4.x`

### What did you see instead?

```
[E] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   at Shadowsocks.Program.Main()
```

### remark

The system unexpectedly shutdown and the alert shows when I restart the system and launch shadowsocks executable. I updated the shadowcocks.exe file using the latest release. same error.

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1185#issuecomment-308097718
