### ISSUE TITLE
SS Exception - LoadCurrentConfiguration()

### ISSUE THREAD

**Issue by Sya-san** [shadowsocks/shadowsocks-windows#1233]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4.0

### Environment(Operating system, .NET Framework, etc)
w7 x64 .net 4.7(setup .net 4.0 first and then .net 4.7)

### Steps you have tried
start Shadowsocks.exe -- 正向代理设置  -- bug 

### What did you expect to see?
[2017-07-12 09:44:23] Shadowsocks started
[2017-07-12 09:44:57] [E] Exception Detail: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.View.ProxyForm.LoadCurrentConfiguration()
   at Shadowsocks.View.ProxyForm..ctor(ShadowsocksController controller)
   at Shadowsocks.View.MenuViewController.ShowProxyForm()
   at Shadowsocks.View.MenuViewController.proxyItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Command.DispatchID(Int32 id)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

### What did you see instead?
 the same as above 

### Config and error log in detail (with all sensitive info masked)
not any config , new downloaded , error log  the same as above

**Comment by celeron533** [comment]
可能和 #1236 类似原因引发，请先设定一台服务器，让本客户端生成config文件后再做其他操作。
