### ISSUE TITLE
PC Shadowsocks not working since yesterday, but  IOS/andriod no problem.

### ISSUE THREAD

**Issue by dopreme** [shadowsocks/shadowsocks-windows#1238]
My friend's and my windows SS not working since yesterday, but both our IOS/ Android SS still fine with the VPS servers, so it's not our VPS problem. Can anybody help please.

### Version(release version or AppVeyor link)
2.3 / 2.5.6

### Environment(Operating system, .NET Framework, etc)
XP, Net framework 2.0/3.0/4.5

### What did you see instead?
 at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
[2017-07-15 09:10:15] System.Net.Sockets.SocketException (0x80004005): 由于目标机器积极拒绝，无法连接。 xxx.xx.xx.xxx:5353
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
[2017-07-15 09:10:15] System.Net.Sockets.SocketException (0x80004005): 由于目标机器积极拒绝，无法连接。 xxx.xx.xx.xxx:5353
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
[2017-07-15 09:10:15] xxx.xx.xx.xxx:5353 timed out
[2017-07-15 09:10:15] System.Net.Sockets.SocketException (0x80004005): 由于目标机器积极拒绝，无法连接。 xxx.xx.xx.xxx:5353
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
[2017-07-15 09:10:15] System.Net.Sockets.SocketException (0x80004005): 由于目标机器积极拒绝，无法连接。 xxx.xx.xx.xxx:5353
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
[2017-07-15 09:10:16] xxx.xx.xx.xxx:5353 timed out
[2017-07-15 09:10:16] xxx.xx.xx.xxx:5353 timed out
[2017-07-15 09:10:16] System.Net.Sockets.SocketException (0x80004005): 由于目标机器积极拒绝，无法连接。 xxx.xx.xx.xxx:5353
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
[2017-07-15 09:10:16] System.Net.Sockets.SocketException (0x80004005): 由于目标机器积极拒绝，无法连接。 xxx.xx.xx.xxx:5353
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
[2017-07-15 09:10:16] xxx.xx.xx.xxx:5353timed out
[2017-07-15 09:10:16] xxx.xx.xx.xxx:5353 timed out
[2017-07-15 09:10:16] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at Shadowsocks.Controller.Handler.StartConnect()

**Comment by austinxv** [comment]
**我也一样，，，win10昨天更新后，，，无法连接**
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by celeron533** [comment]
@dopreme 
Some of the encryption algorithm in version 2.5.6 have weakness. Improvements are done in latest release. Your connection issue may caused by:
1. Your VPS provider are using new algorithm which is not available in 2.5.6. Meanwhile you mobile app support it.
2. By using the old algorithm, your server has been exposed to the Big Brother.
3. There maybe a defect.

Please install the latest release and try again.

**Comment by celeron533** [comment]
@austinxv
Are you in the Win 10 Insider Preview?
