### ISSUE TITLE
打开软件后的一个错误：System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by sangbobo** [shadowsocks/shadowsocks-windows#1294]
---------------------------
Shadowsocks non-UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

System.NullReferenceException: Object reference not set to an instance of an object.

   at Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)

   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)

   at Shadowsocks.Controller.ShadowsocksController.Reload()

   at Shadowsocks.Program.Main()

PS：**但是删除客户端下的所有配置文件，重新打开不再出现上述问题。**

**Comment by chenshaoju** [comment]
该问题已知：
https://github.com/shadowsocks/shadowsocks-windows/issues/1178#issuecomment-308097676
