### ISSUE TITLE
非预期错误

### ISSUE THREAD

**Issue by soldierssword** [shadowsocks/shadowsocks-windows#1326]
```
---------------------------
Shadowsocks non-UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)

   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()

   at System.Collections.Generic.List`1.Enumerator.MoveNext()

   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at Shadowsocks.Model.StatisticsRecord..ctor(String identifier, ICollection`1 inboundSpeedRecords, ICollection`1 outboundSpeedRecords, ICollection`1 latencyRecords)

   at Shadowsocks.Controller.AvailabilityStatistics.UpdateRecords()

   at Shadowsocks.Controller.AvailabilityStatistics.Run(Object _)

   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.TimerQueueTimer.CallCallback()

   at System.Threading.TimerQueueTimer.Fire()

   at System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
---------------------------
确定   
---------------------------
```

**Comment by celeron533** [comment]
#906
