### ISSUE TITLE
非预期错误 - Font

### ISSUE THREAD

**Issue by ikumi2** [shadowsocks/shadowsocks-windows#1376]
```
[2017-09-11 18:36:34] [E] System.ArgumentException: Font 'Consolas' does not support style 'Regular'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize)
   at Shadowsocks.Model.LogViewerConfig..ctor()
   at Shadowsocks.Model.Configuration.Load()
   at Shadowsocks.Controller.ShadowsocksController..ctor()
   at Shadowsocks.Program.Main()
```

版本4.06
OS Win7
.NET4.6.2

**Comment by celeron533** [comment]
似乎是你的机器没有合适的字体

**Comment by celeron533** [comment]
去`gui-config.json`把font那一段清除后试一试

**Comment by thekingofworld** [comment]
启动的时候报这个错误 ， 都没生成 gui-config.json这个文件，怎么搞？

**Comment by celeron533** [comment]
可能还是你的系统没有consolas regular
![image](https://user-images.githubusercontent.com/3608762/33409185-fee6943a-d5b4-11e7-8953-8efdbf991a85.png)

**Comment by MinhLee92** [comment]
Thanks
