### ISSUE TITLE
Shadowsocks only works inside a internet browser

### ISSUE THREAD

**Issue by GentleRV** [shadowsocks/shadowsocks-windows#1395]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
Version 4.0.6

### Environment(Operating system, .NET Framework, etc)
As needed for Shadowsocks
Win7 x64
### Steps you have tried
Testing with streaming internet audio and several other programs

### What did you expect to see?
In the view log files the inbound traffic if activate audio stream

### What did you see instead?
no incoming traffic

### Config and error log in detail (with all sensitive info masked)

If open website www.nu.nl using shadowsocks, video and pictures are not visible
Open this website direct from a server on location, all is visible
Shadowsocks server is a local server
System proxy only works partly inside internet browsers, not for the client computer as general proxy
I hope this will be possible infuture

**Comment by GentleRV** [comment]
I added a part of the log file.

**Comment by GentleRV** [comment]
[2017-09-06 15:05:11] Shadowsocks started
[2017-09-06 15:05:56] Shadowsocks started
[2017-09-06 15:06:00] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
Please check your server IP,Port,password and method is correct.
If your server is build by your self,Please check firewall (iptables) etc...

**Comment by paperbag** [comment]
First of all, the reason why the pirtures and videos can not display is that `media.nu.nl` was blocked.
You could add the following rules in your `user-rule.txt` or use global mode.

```
||media.nu.nl^
||global.ib-ibi.com^
```


The question about the proxy only work on browser:
You should set proxy for your software. 
This link is example of Tencent QQ: http://kf.qq.com/faq/120322fu63YV130422FJnAJV.html
If you can't find settings like that, may be your software not support proxy.

**Comment by GentleRV** [comment]
@paperbag,

Thanks, In global mode all is working fine but get a lot of advertising.
The rule for the PAC files are clear to me, the only thing I dont like it the mandatory update fromout github. I can change what I want, later all will be overruled by the GFWlist
In my system I have a hosts file with all not wanted sites in there, I transferred this contents to the user rules file.
Still have problems with other sites as they are in the GFWlist.

About proxy use:
As system wide proxy I would like that all traffic from this local windows client go thru the shadowsocks connection, many programs don't have a proxy menu .....like my old winamp streaming internet radio
I must say shadowsocks is crazy fast

**Comment by paperbag** [comment]
> the only thing I dont like it the mandatory update fromout github. I can change what I want, later all will be overruled by the GFWlist.

https://github.com/shadowsocks/shadowsocks-windows/issues/1354

> many programs don't have a proxy menu.

You can try VRouter. It sounds good. (But I haven't tried it yet.) 
link: https://github.com/icymind/VRouter

Hope that helps. @GentleRV
