### ISSUE TITLE
System.Net.Sockets.SocketException (0x80004005): 请求的名称有效，但是找不到请求的类型的数据。

### ISSUE THREAD

**Issue by TongJiankang** [shadowsocks/shadowsocks-windows#1433]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
shadowsocks 4.0.6

### Environment(Operating system, .NET Framework, etc)
win 7 64位
 .NET Framework 4.6.2

### Steps you have tried

管理员执行
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
重新安装
 .NET Framework 4.6.2
shadowsocks 4.0.6

### What did you see instead?

![image](https://user-images.githubusercontent.com/9145246/31367986-684c181c-adad-11e7-92ca-8d0d14e1f06d.png)

### Config and error log in detail (with all sensitive info masked)
```
[2017-10-10 11:09:30] connect to info.pinyin.sogou.com:80
[2017-10-10 11:09:32] System.Net.Sockets.SocketException (0x80004005): 请求的名称有效，但是找不到请求的类型的数据。
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2017-10-10 11:09:46] connect to clientservices.googleapis.com:443
[2017-10-10 11:09:48] connect to clients4.google.com:443
[2017-10-10 11:09:48] System.Net.Sockets.SocketException (0x80004005): 请求的名称有效，但是找不到请求的类型的数据。
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2017-10-10 11:09:50] System.Net.Sockets.SocketException (0x80004005): 请求的名称有效，但是找不到请求的类型的数据。
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
```

**Comment by TongJiankang** [comment]
找到问题了，代理服务器的问题
