### ISSUE TITLE
单元测试跑不通

### ISSUE THREAD

**Issue by albertofwb** [shadowsocks/shadowsocks-windows#1495]
win10
vs2017
.net 4.6.2
git version 7c73aaa1cfdc6b

跑单元测试的时候，每次调用GetTempPath() 其中的 Application.StartupPath = "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO 14.0\\COMMON7\\IDE\\COMMONEXTENSIONS\\MICROSOFT\\TESTWINDOW"
因为权限问题导致单元测试失败。

虽然可以手动设置 GetTempPath() 中的路径，但始终觉得这样不优雅
或者使用管理员身份运行，应该就能跑通，但仍觉得不妙

不知道你们有没有遇到过这个问题？

这篇帖子记录了同样的问题，好像是vs的锅
https://www.pcreview.co.uk/threads/problem-with-system-windows-forms-application-startuppath-when-running-test-project.3281721/
```
System.TypeInitializationException: The type initializer for 'Shadowsocks.Encryption.MbedTLS' threw an exception. ---> System.UnauthorizedAccessException: Access to the path 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\ss_win_temp' is denied.

Test Name:	TestMbedTLSEncryption
Test FullName:	test.UnitTest.TestMbedTLSEncryption
Test Source:	C:\Users\WangBiao\Documents\GitRepos\community\ss\shadowsocks-windows\test\UnitTest.cs : line 110
Test Outcome:	Failed
Test Duration:	0:00:00.0087746

Result StackTrace:	
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Shadowsocks.Util.Utils.GetTempPath() in C:\Users\WangBiao\Documents\GitRepos\community\ss\shadowsocks-windows\shadowsocks-csharp\Util\Util.cs:line 44
   at Shadowsocks.Util.Utils.GetTempPath(String filename) in C:\Users\WangBiao\Documents\GitRepos\community\ss\shadowsocks-windows\shadowsocks-csharp\Util\Util.cs:line 53
   at Shadowsocks.Encryption.MbedTLS..cctor() in C:\Users\WangBiao\Documents\GitRepos\community\ss\shadowsocks-windows\shadowsocks-csharp\Encryption\MbedTLS.cs:line 19
 --- End of inner exception stack trace ---
    at Shadowsocks.Encryption.MbedTLS.MD5(Byte[] input)
   at Shadowsocks.Encryption.Stream.StreamEncryptor.LegacyDeriveKey(Byte[] password, Byte[] key, Int32 keylen) in C:\Users\WangBiao\Documents\GitRepos\community\ss\shadowsocks-windows\shadowsocks-csharp\Encryption\Stream\StreamEncryptor.cs:line 78
   at Shadowsocks.Encryption.Stream.StreamEncryptor.InitKey(String password) in C:\Users\WangBiao\Documents\GitRepos\community\ss\shadowsocks-windows\shadowsocks-csharp\Encryption\Stream\StreamEncryptor.cs:line 68
   at Shadowsocks.Encryption.Stream.StreamEncryptor..ctor(String method, String password) in C:\Users\WangBiao\Documents\GitRepos\community\ss\shadowsocks-windows\shadowsocks-csharp\Encryption\Stream\StreamEncryptor.cs:line 43
   at Shadowsocks.Encryption.Stream.StreamMbedTLSEncryptor..ctor(String method, String password) in C:\Users\WangBiao\Documents\GitRepos\community\ss\shadowsocks-windows\shadowsocks-csharp\Encryption\Stream\StreamMbedTLSEncryptor.cs:line 20
   at test.UnitTest.RunSingleMbedTLSEncryptionThread() in C:\Users\WangBiao\Documents\GitRepos\community\ss\shadowsocks-windows\test\UnitTest.cs:line 144
   at test.UnitTest.TestMbedTLSEncryption() in C:\Users\WangBiao\Documents\GitRepos\community\ss\shadowsocks-windows\test\UnitTest.cs:line 112
Result Message:	
Test method test.UnitTest.TestMbedTLSEncryption threw exception: 
```

**Comment by chenshaoju** [comment]
你好，从Windows Vsita开始，由于UAC的保护，一般账户是没有权限往C:\Program Files\ 和 C:\Program Files (x86)\ 目录下写入文件的。

**Comment by albertofwb** [comment]
所以只能用管理员权限来跑单元测试吗？

**Comment by celeron533** [comment]
CI上由于权限放得比较松（沙箱），所有没有问题，但一般在本地按照默认来跑这个测试基本都有这个问题。
以下任一方法应该有用：
1. 管理员权限开VS
2. 复制必要的dll到测试执行文件夹
3. 放宽测试执行文件夹权限
