### ISSUE TITLE
500 Internal Privoxy Error

### ISSUE THREAD

**Issue by eahau** [shadowsocks/shadowsocks-windows#1541]
![image](https://user-images.githubusercontent.com/23614225/33381045-d9acdeb6-d557-11e7-818e-54954f692d2a.png)
windows能ping通远程主机的网络ip，远程主机可以ping通谷歌，报这个错误，谁遇到过啊？请问怎么解决的？

**Comment by networkthroughput** [comment]
检查你的密码,端口,加密方式是否正确.
以及,你服务器的iptables防火墙配置是否正确.

**Comment by eahau** [comment]
密码，端口，加密方式肯定正确；防火墙关闭了。。。

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1345#issuecomment-326476709

**Comment by chenshaoju** [comment]
SS的日志里有写什么吗？

**Comment by eahau** [comment]
@chenshaoju 日志如下：
2017-11-28 15:03:38 INFO     starting server at 13.114.62.205:8388
Traceback (most recent call last):
  File "/usr/local/bin/ssserver", line 9, in <module>
    load_entry_point('shadowsocks==2.8.2', 'console_scripts', 'ssserver')()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/server.py", line 68, in main
    tcp_servers.append(tcprelay.TCPRelay(a_config, dns_resolver, False))
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/tcprelay.py", line 582, in __init__
    server_socket.bind(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
2017-11-29 14:05:15 INFO     starting server at 0.0.0.0:443
2017-11-30 12:12:09 INFO     starting server at 0.0.0.0:8388
2017-11-30 12:13:25 INFO     starting server at 0.0.0.0:8388

**Comment by chenshaoju** [comment]
已知默认的8388端口被重点关照，换端口。

**Comment by eahau** [comment]
@chenshaoju 换了端口也不行啊~

**Comment by eahau** [comment]
@chenshaoju AWS换成redhat实例就好了，之前是ubuntu，总之谢谢~
