### ISSUE TITLE
500 Internal Privoxy Error

### ISSUE THREAD

**Issue by neversleep007** [shadowsocks/shadowsocks-windows#1566]
页面是这么显示的：
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:
Could not load template file no-server-data or one of its included components.
Please contact your proxy administrator.
If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

logs是这么显示的：
[2017-12-12 01:06:31] Shadowsocks started
[2017-12-12 01:07:16] Shadowsocks started
[2017-12-12 01:07:19] System.Net.Sockets.SocketException (0x80004005): No such host is known
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

然后那个添加服务器的QR在哪里，我貌似上不了你们官网。谢谢。

**Comment by chenshaoju** [comment]
```
No such host is known
```
这意味着你使用的服务器的域名被停止解析或者删除解析了。
如果你从某处购买的SS服务，请与你的SS服务商联系。
也可能你的服务商跑路了。
Shadowsocks for Windows 不提供，也不销售SS服务。
