### ISSUE TITLE
Problem With Opening Shadowsocks

### ISSUE THREAD

**Issue by SmoothRally** [shadowsocks/shadowsocks-windows#1603]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)
[2018-01-01 16:08:12] [E] System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: The specified procedure could not be found
   --- End of inner exception stack trace ---
   at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   at ?A0x721f77f1.CreateCModuleInitialize()
   at ?A0x721f77f1.??__E?A0x721f77f1@cmiStartupRunner@@YMXXZ()
   at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
   at GlobalHotKey.HotKeyManager..ctor()
   at Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)
   at Shadowsocks.Program.Main()
[2018-01-01 16:08:37] [E] System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: The specified procedure could not be found
   --- End of inner exception stack trace ---
   at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   at ?A0x721f77f1.CreateCModuleInitialize()
   at ?A0x721f77f1.??__E?A0x721f77f1@cmiStartupRunner@@YMXXZ()
   at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
   at GlobalHotKey.HotKeyManager..ctor()
   at Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)
   at Shadowsocks.Program.Main()
[2018-01-01 16:08:52] [E] System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: The specified procedure could not be found
   --- End of inner exception stack trace ---
   at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   at ?A0x721f77f1.CreateCModuleInitialize()
   at ?A0x721f77f1.??__E?A0x721f77f1@cmiStartupRunner@@YMXXZ()
   at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
   at GlobalHotKey.HotKeyManager..ctor()
   at Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)
   at Shadowsocks.Program.Main()
[2018-01-01 16:09:16] [E] System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: The specified procedure could not be found
   --- End of inner exception stack trace ---
   at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   at ?A0x721f77f1.CreateCModuleInitialize()
   at ?A0x721f77f1.??__E?A0x721f77f1@cmiStartupRunner@@YMXXZ()
   at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
   at GlobalHotKey.HotKeyManager..ctor()
   at Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)
   at Shadowsocks.Program.Main()

**Comment by chenshaoju** [comment]
Please Reinstall .NET framework 4.7.1 or newer NET framework. 
https://www.microsoft.com/net/download/thank-you/net471

read more: https://github.com/shadowsocks/shadowsocks-windows/issues/1399
