### ISSUE TITLE
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效

### ISSUE THREAD

**Issue by coderkiller** [shadowsocks/shadowsocks-windows#1606]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.0 和4.0.7都是这样的情况

### Environment(Operating system, .NET Framework, etc)
win10 .net 已更新
### Steps you have tried
朋友在他的电脑上使用相同的配置正常翻墙。
本机出现如下错误。
连接主机 timeout

### Config and error log in detail (with all sensitive info masked)
[2018-01-02 16:59:26] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
这意味着你的服务器可能被墙了或者配置不正确。

请尝试使用 tcping 来检测到你的服务器端口通信是否正常，如果你的服务器是自己搭的，用的是默认的端口，请换一个。

参考阅读： https://github.com/shadowsocks/shadowsocks-windows/issues/1510

**Comment by nomadturk** [comment]
How do we fix it?

On my Windows 10 computer I can't use it either.

(The server pings back. Port is open as well. I can connect to the server on my phone just fine. Not with this one though...)


The second I try something I get the error below. I can not use it on my computer at all:

```
[2018-01-16 21:24:20] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

```

**Comment by chenshaoju** [comment]
@nomadturk Please make sure is same config with your computer and phone.

If everything is same, execute  cmd.exe or powershell in administrator,and run:
```
netsh interface ipv4 reset
netsh interface ipv6 reset
nseth winsock reset
```
after done, reboot computer.

**Comment by nomadturk** [comment]
@chenshaoju 

Strange, this fixed it.
Even though config was same, I was having trouble connecting.
Now after I did this, it works.

Even without a reboot, it did.

**Comment by 972934564** [comment]
> @chenshaoju
> 
> Strange, this fixed it.
> Even though config was same, I was having trouble connecting.
> Now after I did this, it works.
> 
> Even without a reboot, it did.

I have tried,But it didnt work,I dont know why

**Comment by chenshaoju** [comment]
Please use 3rd-party TCP test software test your connection : https://github.com/shadowsocks/shadowsocks-windows/issues/2314

**Comment by Felix-Indoing** [comment]
Confirm this problem caused by shanghai ICP detect raw SS protocol, just use obfs plugin and it works.
