### ISSUE TITLE
shadowsocks-windows-4.0.7 上不了

### ISSUE THREAD

**Issue by afmnnn** [shadowsocks/shadowsocks-windows#1635]
shadowsocks-windows-4.0.7 
通过https://freess.cx/ 扫二维码 使用全局模式不能上国外网站
 pac模式下 有时能上部分网站 
win7 64位 前几天开始这样的 之前好好的都能用 现在不知什么问题

**Comment by jw587** [comment]
我也是用的4.0.7，一直没有什么问题，估计是你的ss账号的问题。

**Comment by afmnnn** [comment]
@jw587 这软件没有帐号的吧...

**Comment by afmnnn** [comment]
[2018-01-21 21:05:51] us03.fss.fun:17929 timed out
[2018-01-21 21:05:55] Shadowsocks started
[2018-01-21 21:05:55] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
The underlying connection was closed，基础连接已关闭，你用的服务器的端口被墙了，请与你的SS服务商联系。

**Comment by networkthroughput** [comment]
你用个免费的ss代理,还期待什么稳定性?

**Comment by jw587** [comment]
错误日志中有Authentication failed，验证失败，说明你那个二维码已经过期了，freess那个网站分享的二维码就几个小时的有效期，过期后得扫新的二维码，建议你自己搭服务器。
