### ISSUE TITLE
Win10突然不能使用SS

### ISSUE THREAD

**Issue by mingde816** [shadowsocks/shadowsocks-windows#1652]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.7

### Environment(Operating system, .NET Framework, etc)

Win10
### Steps you have tried

删除后重新安装
### What did you expect to see?

启动全局代理也无效
### What did you see instead?
重复出现以下错误，不能成功代理

### Config and error log in detail (with all sensitive info masked)
[2018-02-01 00:41:00] System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Shadowsocks.Util.Sockets.WrappedSocket.Shutdown(SocketShutdown how)
   at Shadowsocks.Proxy.DirectConnect.Shutdown(SocketShutdown how)
   at Shadowsocks.Controller.TCPHandler.Close()
[2018-02-01 00:41:00] System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Shadowsocks.Util.Sockets.WrappedSocket.Shutdown(SocketShutdown how)
   at Shadowsocks.Proxy.DirectConnect.Shutdown(SocketShutdown how)
   at Shadowsocks.Controller.TCPHandler.Close()

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1617

**Comment by mingde816** [comment]
Windows下哪有shadowsocks.json？怎么修改为"server":"::"
是说的服务器端吗？

**Comment by chenshaoju** [comment]
噢，你是自己搭的SS服务还是买的？

Ping你的域名（如果是），解析出来的IP地址是IPv4格式的还是IPv6格式的？

**Comment by mingde816** [comment]
买的SS服务，Linode，手机端测试线路是可以的。
Ping域名出来的是IPv4的格式，应该不是域名解析的问题，替换成IP也是一样的错误。

**Comment by chenshaoju** [comment]
请尝试在编辑服务器界面将右下角的代理端口号换一个看看，比如 10800 ？

**Comment by mingde816** [comment]
好吧。谢谢，果然是端口的问题。。。
我本来就是自定义的端口1086，所以没想到会有冲突，改了端口可以了，thanks

**Comment by mingde816** [comment]
这个问题在win10系统更新后再次发生 @chenshaoju 
并不是端口的问题，端口改了n个，依旧无效。
mac 和iPhone不受影响

**Comment by chenshaoju** [comment]
请尝试以管理员身份启动命令提示符（ｃｍｄ）或PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一个，三行执行完毕后重新启动计算机后再看看。
