### ISSUE TITLE
I can't connect using my Win 7, but my android works fine. My browser says: 500 Internal Privoxy Error

### ISSUE THREAD

**Issue by echoscope** [shadowsocks/shadowsocks-windows#1688]
Version: Shadowsocks 4.0.8

Environment：
1 Windows 7, 64 bit
2 Antivirus Software: 腾讯电脑管家
3 Browser: Chrome, I uninstalled IE

Problem:
I can visit Google and other websites using my SAMSUNG with newest Shadowsocks.
But I can't visit with the same server at my Win 7, My Browser says: 500 Internal Privoxy Error
==========
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).
=========

Below are logs of Shadowsoks (I hid my server ip):
=========
[2018-02-20 04:09:33] connect to api.github.com:443
[2018-02-20 04:09:33] Socket connected to ss server: ***.***.***.***:*
[2018-02-20 04:09:40] connect to www.google.com:80
[2018-02-20 04:09:40] Socket connected to ss server: ***.***.***.***:*
[2018-02-20 04:09:41] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
==========END

So, what I can do?

**Comment by echoscope** [comment]
嗯...字号怎么乱了...

**Comment by chenshaoju** [comment]
Try Ping your server IP on your PC, Can get responses?

**Comment by echoscope** [comment]
@chenshaoju Yes.

**Comment by chenshaoju** [comment]
This issue looks same: https://github.com/shadowsocks/shadowsocks-windows/issues/1635

Please make sure is the same config with your phone and PC, And on the same network.

This highly possible port is wrong, or your port has been blocked.

Try using TCPing check your port connectivity on your PC: https://www.elifulkerson.com/projects/tcping.php

eg.
```
tcping 123.45.67.89 9876
```

**Comment by echoscope** [comment]
@chenshaoju I checked my port like you said, but there is no problem. Four times probing, all were open. And I tried twice, all successful.

**Comment by chenshaoju** [comment]
Please try run these command on cmd or PowerShell as Administrator:
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```

After finish 3 commands, reboot computer.

**Comment by echoscope** [comment]
@chenshaoju uh... the error remains.

**Comment by chenshaoju** [comment]
If config is same, And on the same network, Phone is fine but PC not working...

Odd... I don't know.

**Comment by echoscope** [comment]
@chenshaoju OK, I'll try other ways. Thank you for your patience : )
