### ISSUE TITLE
Mac和iPhone都能用，但是Windows连不上

### ISSUE THREAD

**Issue by Zihin** [shadowsocks/shadowsocks-windows#1705]
我的Mac和iPhone都能用shadowsocks，但是Windows总是连不上，具体日志如下，我也不知道是什么问题，重置过Windows系统的网络设置还有代理设置好几遍了，也没有用。
shadowsocks.log
```
System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 127.0.0.1:1080
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
```

**Comment by chenshaoju** [comment]
该问题很高的可能性和系统有关，请尝试 ping 127.0.0.1 ，能通吗？

参考阅读： https://github.com/shadowsocks/shadowsocks-windows/issues/1551

**Comment by mingde816** [comment]
问题一样，错误一样。

**Comment by Zihin** [comment]
@chenshaoju ping 不通

**Comment by chenshaoju** [comment]
127.0.0.1 是本地环回地址，如果该地址Ping不通的话，很高的可能性是你的TCP/IP协议栈有问题或者某些软件干扰／屏蔽了。

请尝试以管理员身份启动命令提示符（ｃｍｄ）或PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一个，三行执行完毕后重启看看。

如果仍然不行，你可能需要重置系统。

**Comment by Zihin** [comment]
@chenshaoju 谢谢啦~  我弄好了  是防火墙的问题，我关闭防火墙就好了。
