### ISSUE TITLE
越新版连接被拒越严重

### ISSUE THREAD

**Issue by Johntall** [shadowsocks/shadowsocks-windows#1781]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win7

### Steps you have tried / 操作步骤
打开ss, 连接服务器

### What did you expect to see? / 期望的结果
连上

### What did you see instead? / 实际结果
System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
经常经被拒连. 偶尔连上.有20几个服务器, 一个一个换过去, 偶尔能连上, 不固定某个
但手机上用的ss连接成功率基本100%
补充说明: 手机在同网wifi
win7已关防火墙
连接有50%被拒, 40% time out,  10%连上, 旧版成功率高一些, 可能30%吧
这个问题以前一直存在, 我一直都不知道是什么原因
每次只要连上一直用可以一直不出问题, 只要重边了基本就又要试几十几次了
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

日志
----
[2018-03-29 15:01:57] HA switching to server: #17 台湾节点 (xxxxxxxxxxxxxxxxxx)
[2018-03-29 15:02:02] #17 台湾节点 (xxxxxxxxxxxxxxxxxx) timed out
[2018-03-29 15:02:11] HA switching to server: #16 台湾节点 (xxxxxxxxxxxxxxxxx)
[2018-03-29 15:02:14] HA switching to server: #15 新加坡节点 (xxxxxxxxxxxxxxxxxxxxxx)
[2018-03-29 15:02:15] HA switching to server: #14 新加坡节点 (xxxxxxxxxxxxxxxxx)
[2018-03-29 15:02:16] HA switching to server: #13 新加坡节点 (xxxxxxxxxxxxxxxxxx)
[2018-03-29 15:02:21] #13 新加坡节点 (xxx.xxx.xxx.xxx:xxxxxx1) timed out
[2018-03-29 15:02:21] #13 新加坡节点 (xxxxxxxxxxxxxxxxxxxxx) timed out
[2018-03-29 15:04:14] HA switching to server: #12 香港节点 (xxxxxxxxxxxxxxxxxxx)
[2018-03-29 15:04:18] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

=================================================
下面是配置文件的一部分(删去服务器信息后剩下的)
----
"strategy": "com.shadowsocks.strategy.ha",
  "index": -1,
  "global": false,
  "enabled": true,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1080,
  "pacUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": true,
  "autoCheckUpdate": false,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": {
    "topMost": true,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3
  },
  "hotkey": {
    "SwitchSystemProxy": "Ctrl+P",
    "SwitchSystemProxyMode": "Ctrl+Shift+P",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": ""
  }
}

**Comment by Johntall** [comment]
补充说明: 手机在同网wifi
win7已关防火墙
连接有50%被拒, 40% time out,  10%连上, 旧版成功率高一些, 可能30%吧

===================================
[2018-03-29 15:01:57] HA switching to server: #17 台湾节点 (xxxxxxxxxxxxxxxxxx)
[2018-03-29 15:02:02] #17 台湾节点 (xxxxxxxxxxxxxxxxxx) timed out
[2018-03-29 15:02:11] HA switching to server: #16 台湾节点 (xxxxxxxxxxxxxxxxx)
[2018-03-29 15:02:14] HA switching to server: #15 新加坡节点 (xxxxxxxxxxxxxxxxxxxxxx)
[2018-03-29 15:02:15] HA switching to server: #14 新加坡节点 (xxxxxxxxxxxxxxxxx)
[2018-03-29 15:02:16] HA switching to server: #13 新加坡节点 (xxxxxxxxxxxxxxxxxx)
[2018-03-29 15:02:21] #13 新加坡节点 (xxx.xxx.xxx.xxx:xxxxxx1) timed out
[2018-03-29 15:02:21] #13 新加坡节点 (xxxxxxxxxxxxxxxxxxxxx) timed out
[2018-03-29 15:04:14] HA switching to server: #12 香港节点 (xxxxxxxxxxxxxxxxxxx)
[2018-03-29 15:04:18] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by Johntall** [comment]
这个问题以前一直存在, 我一直都不知道是什么原因

每次只要连上一直用可以一直不出问题, 只要重边了基本就又要试几十几次了

**Comment by chenshaoju** [comment]
你好，这看起来很像是你的服务商的服务器有问题。

timed out 意味着你所连接的服务器不存在，或者被墙了。

由于目标计算机积极拒绝，无法连接，意味着你所连接的服务器存在，但是端口不通（端口没打开）

请访问你的服务商网站更新你的服务器列表、获取帮助。

**Comment by Johntall** [comment]
谢谢你
我手机用的一直是那一堆中固定的一个, 基本上都能连上, 很奇怪
我回想了一下, 我一直把上一版本的gui-config.json拷到新版里, 刚才比较了一下4.0.9版自动生成的和4.0.7,
"availabilityStatistics": false,这个变化了, 不知道是不是有关系

还有想请教一下现在新版会自动生成一个temp目录, 里面好几个文件, 是用来做啥的?

**Comment by chenshaoju** [comment]
```availabilityStatistics``` 是统计连接状态的一个功能，但是这个功能有问题，会导致崩溃，建议不要开启（使用 false ）。

ss_win_temp 下的文件：
```
libcrypto-1_1.dll - 加密库
libsscrypto.dll - 加密库
mgwz.dll - Privoxy所需的动态库
privoxy_<随机数>.conf - Privoxy配置文件
shadowsocks.log - SS本身的日志
ss_privoxy.exe - Privoxy主程序
ss_privoxy.log - Privoxy的日志
sysproxy.exe - 用于系统代理的代理设置程序
```

**Comment by sumirecccp** [comment]
这个问题我也遇到过，貌似是由于服务器负载过大引起的 过大的情况下就会频繁崩溃或拒连 可以考虑修改一下ss服务器端配置文件的worker数

**Comment by chenshaoju** [comment]
如果你是自己搭的服务器，请尝试使用此 sysctl.conf ： https://gist.github.com/chenshaoju/b0e20f23efabb8eb2cd4

关键是 ```net.ipv4.tcp_congestion_control = hybla``` 这一行。

**Comment by Johntall** [comment]
大概猜出原因了: 
服务器的连接数到达设定上限, 就拒绝新来的连接, 毕境这是买的便宜货,  服务器好象还设定了60秒无使用就会断开连接.不过一连上只要持续传输倒是速度很快,没有什么问题.
谢谢大家
