### ISSUE TITLE
非预期错误

### ISSUE THREAD

**Issue by Tesor** [shadowsocks/shadowsocks-windows#1797]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
version：4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Microsoft .NET Framework 4.6.2, Microsoft Visual C++ 2015 Redistributable (x86)已安装
Win7
### Steps you have tried / 操作步骤
双击exe文件

### What did you expect to see? / 期望的结果
正常打开exe

### What did you see instead? / 实际结果
![image](https://user-images.githubusercontent.com/38068765/38299691-60b020f2-382d-11e8-9961-3b85658c89df.png)

System.ArgumentException: Font 'Consolas' does not support
style 'Regular'.
at System.Drawing.Font.CreateNativeFont
at System.Drawing.Font.Initialize(Font Family family, Single
emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet,
Boolean gdiVerticalFont)
at System.Drawing.Font.Initialize(String familyName, Single
emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet,
Boolean gdiVerticalFont)
at System.Drawing.Font..ctor(String familyName, Single emSize)
at Shadowsocks.Model.LogViewerConfig..ctor()
at Shadowsocks.Model.Configuration.Load()
at Shadowsocks.Controller.ShadowsocksController..ctor()
at Shadowsocks.Program.Main()

**Comment by Tesor** [comment]
已解决，close
