### ISSUE TITLE
PC无法使用，手机端可以正常使用

### ISSUE THREAD

**Issue by kurobanekid** [shadowsocks/shadowsocks-windows#1837]
### Version(release version or AppVeyor link) / 版本
正式版 v4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境
windows 10 1803 (OS Build 17134.1) 
.NET Framework v4.0.30319

### Steps you have tried / 操作步骤
Windows更新到1803版本后，PC端无法使用，手机没有问题
有两个服务器，一个自己搭，一个自动搭，两个都是PC端无法使用，手机没有问题
**但**在FF中设置如下，却可以在FF中科学上网
![](https://user-images.githubusercontent.com/515763/37390878-680ff942-27a4-11e8-81f1-54edfe7658d9.png)

### What did you expect to see? / 期望的结果
在PC端科学上网

### What did you see instead? / 实际结果
无法通过PC端实现科学上网

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件
```
2018-05-04 14:53:32] Shadowsocks started
[2018-05-04 14:53:32] 
=========================

Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-05-04 14:53:36] System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2018-05-04 14:53:36] System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2018-05-04 14:53:36] System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2018-05-04 14:53:36] System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2018-05-04 14:53:36] System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
```

**Comment by chenshaoju** [comment]
你好，我的Win10也更新到了 1803 ，但是并没有该问题。

![2018-05-04 1](https://user-images.githubusercontent.com/515763/39617890-fa52bb00-4fb3-11e8-9bc5-a10cbbd24b39.png)


我怀疑这个问题和PAC有关，你能否尝试一下全局模式，是否工作正常？如果你有Chrome，在SS工作在PAC模式的情况下，用Chrome打开 chrome://net-internals/#proxy ，显示的什么？

**Comment by kurobanekid** [comment]
全局模式，无法正常工作
下面是Chrome(V66)下的proxy情况
![snipaste20180504_160321](https://user-images.githubusercontent.com/15232298/39618106-b9a21492-4fb4-11e8-8575-0d53917f6384.png)

**Comment by chenshaoju** [comment]
看起来并没有任何问题，在上图中的情况下，Chrome能否工作？

**Comment by kurobanekid** [comment]
不能😂

**Comment by chenshaoju** [comment]
Hmmm....如果Firefox在手动模式下能工作，很可能是系统问题，由于某些原因，系统无法使用代理了。

这种问题不常见，但是也有类似报告，似乎无解。

请尝试执行这三条命令，看看能否恢复： https://github.com/shadowsocks/shadowsocks-windows/issues/1775#issuecomment-376602737

如果仍然不能，在某些情况下，会莫名其妙的好了。

要是很着急，可能需要重置系统看看。

**Comment by kurobanekid** [comment]
还是不行哈，看来要等下次系统更新了
