### ISSUE TITLE
使用obfs插件总是报错

### ISSUE THREAD

**Issue by zyf2008Neptune** [shadowsocks/shadowsocks-windows#1928]
### Shadowsocks version / 影梭版本
4.0.10

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 1803

### Steps you have tried / 操作步骤
使用obfs插件

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2018-07-14 15:29:08] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2018-07-14 15:29:49] Started SIP003 plugin for xxx on 127.0.0.1:62356 - PID: 10876

**Comment by chenshaoju** [comment]
``` Authentication failed because the remote party has closed the transport stream. ```
这意味着三种可能：
１.你的密码、加密方式、混淆方式（TLS/HTTP）配置有问题，请仔细检查你的配置是否一致
２.你的端口被屏蔽了，请使用tcping进行测试，具体请参阅：  https://github.com/shadowsocks/shadowsocks-windows/issues/1916#issuecomment-403188895
３.你的服务端配置有问题，请确保你访问的是obfs的端口，而非你SS服务的端口。

**Comment by zyf2008Neptune** [comment]
@chenshaoju 
1、2检查过了没问题
请问3具体指什么啊？

**Comment by chenshaoju** [comment]
你的simple-obfs配置是写在 shadowsocks.json 里的，还是独立运行的？

如果是写在 shadowsocks.json 里，应该不会有该问题，如果是独立运行的，请确保端口正确、不冲突。

**Comment by zyf2008Neptune** [comment]
@chenshaoju 
在json里的

**Comment by jasonliul** [comment]
偶尔出错, 自动退出...
俺也遇见过几回.

**Comment by zyf2008Neptune** [comment]
@chenshaoju 
服务端重新设置了，虽然能用了，但仍然报错。。。

**Comment by chenshaoju** [comment]
是和上面相同的错误吗？我开始怀疑是不是你本机的错误。能否换个代理端口看看，就在编辑服务器界面。
