### ISSUE TITLE
ssr pac模式打不开网页

### ISSUE THREAD

**Issue by ACC839303568** [shadowsocks/shadowsocks-windows#1980]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
ShadowsocksR-4.7.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 Pro
.NET Framework 4.7.1

### Steps you have tried / 操作步骤
我学校有一个pulse secure （vpn），之前用这个查知网，查完关掉，ssr切换之后，
用 mode 的 disable system proxy（只能浏览国内网页）没有任何问题，
用pac模式，ie国内国外网页都不行（见下图），chrome国内的网站能上，国外的网站（比如google）上不了。
![image](https://user-images.githubusercontent.com/32789300/44339655-c589a180-a4b4-11e8-8e14-36ca95bbb413.png)
chrome地址栏我默认google，但是我发现，只要在地址栏打上东西，google搜索打不开；选中网页某部分文字，右键google搜索“xxx”，却能打开google。除此之外，直接打开twitter打不开。
我试过dns改为1.1.1.1/1.0.0.1；114.114.114.114/223.5.5.5（百度的方法）但没用。
我试过ipconfig/flushdns，但也没用。
我把那个vpn卸了，win10设置里重置网络，ie里面reset internet explorer settings也没用。
我试过更改ie设置里的LAN，把所有的√全去掉了，好了一小会，但是ssr改模式之后，再换回来与否都不行。

### What did you expect to see? / 期望的结果
正常情况下，ssr pac模式 ie chrome访问国内国外网站都可以，global模式也是（相对于我而言，国内屏蔽国外访问的网站我还没接触过所以基本都能打开）

### What did you see instead? / 实际结果
如上。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2018-08-20 17:32:54] [Error] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 127.0.0.1:1080
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2018-08-20 17:50:47] ShadowsocksR started on port 1080
[2018-08-20 17:51:18] [Error] connect to update server error
[2018-08-20 19:50:08] ShadowsocksR started on port 1080
[2018-08-20 19:50:39] [Error] connect to update server error
[2018-08-20 19:52:24] ShadowsocksR started on port 1080
[2018-08-20 19:52:55] [Error] connect to update server error
[2018-08-20 19:57:55] [Error] connect to update server error

这是最近的信息，其余的和后面这几行都一样。

**Comment by ACC839303568** [comment]
嗯。
Windows系统设置里的proxy项目也有√。我开着pac去掉了，一切正常。
但是我一切换mode，设置里还会有√显示，比如只要我切换到pac模式，就会显示这个，chrome我上不了google等国外网站。
![image](https://user-images.githubusercontent.com/32789300/44340297-ff5ba780-a4b6-11e8-879f-a5aa8959b632.png)
只要我切换到global模式，就会显示这个，ie chrome啥网站都打不开。

![image](https://user-images.githubusercontent.com/32789300/44340381-35992700-a4b7-11e8-8c21-69c47cac6432.png)
只要去掉这些√，我就能正常使用。也就是说，有程序在切换的时候修改了这里。
这该如何是好？

**Comment by studentmain** [comment]
去隔壁ShadowsocksR问。ss不是ssr

**Comment by chenshaoju** [comment]
你Ping 127.0.0.1 ，能通吗？

如果不通，该问题和系统TCP/IP协议栈损坏有关，可能无解，你可能需要重置系统。
