### ISSUE TITLE
不断地timed out。详细情形请进来看日志。System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by yyuekirin** [shadowsocks/shadowsocks-windows#2063]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
Shadowsocks-4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows10 64位版本

### What did you see instead? / 实际结果
首先可以排除搬瓦工端口被封的情况，因为我的第二台电脑和手机同样的设置都可以正常科学上网。
试过ping 127.0.0.1，可以ping得通。

查过issue, #1574 和 #1606 相关。
尝试过
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```

问题仍然无法解决。
之前也出现过类似的问题 ，但是当时我有两个vps，就使用另一个vps搭的ss应急。
过几天后，再切换回原来的出问题这个vps，就可以正常使用了，非常奇怪。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

```
[2018-11-01 10:56:25] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
```

然后下面就是不断地timed out

**Comment by celeron533** [comment]
VPS可能被防火墙间歇性阻断
