### ISSUE TITLE
shadowsocks代理上网

### ISSUE THREAD

**Issue by zhanglc** [shadowsocks/shadowsocks-windows#2072]
公司电脑本身通过代理上网，如果使用shadowsocks呢？是正向代理那个选项么？还是？

**Comment by chenshaoju** [comment]
是的，正向代理那个选项。

![image](https://user-images.githubusercontent.com/515763/48617265-e6d52d80-e9d0-11e8-9206-29e447fb3e98.png)

**Comment by zhanglc** [comment]
我这里是Http 代理，但是总显示代理请求失败，不知道为什么 。

[2018-11-19 09:19:00] connect to clients1.google.com:443
[2018-11-19 09:19:00] Socket connected to proxy 192.168.12.222:63233
[2018-11-19 09:19:00] System.Exception: 代理请求失败
   at Shadowsocks.Proxy.HttpProxy.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
请确保你的是HTTP代理而不是HTTPS代理。

**Comment by zhanglc** [comment]
不好意思，回复的晚了，我这里这个软件下载不好下，请朋友帮忙下载了一下，下面是测试结果


```
[12:50] Testing Started.
	Proxy Server
	Address:	192.168.12.222:63223
	Protocol:	HTTP
	Authentication: NO

[12:50] Starting: Test 1: Connection to the Proxy Server
[12:50] IP Address: 192.168.12.222
[12:50] Connection established
[12:50] Test passed.
[12:50] Starting: Test 2: Connection through the Proxy Server
[12:50] Connection to www.baidu.com:80 established through the proxy server.
[12:50] A default web page was successfuly loaded.
[12:50] Test passed.
[12:50] Starting: Test 3: Proxy Server latency
[12:50] Latency < 0 ms
[12:50] Test passed.
[12:50] Testing Finished.
```

**Comment by chenshaoju** [comment]
看起来是通的。

如果你的SS不工作，可能你的代理服务器没有被允许访问你的SS。

如果你的服务器是你自己搭的，请尝试将端口换为443或者80看看。

**Comment by zhanglc** [comment]
从请求日志来看，是不是内网代理服务器 `192.168.12.222` 请求 ss服务器有问题？

```
[2018-11-19 14:00:13] Socket connected to proxy 192.168.12.222:63223
[2018-11-19 14:00:13] Socket connected to ss server: ss-ip:443
[2018-11-19 14:00:13] connect to accounts.google.com:443
[2018-11-19 14:00:13] Socket connected to proxy 192.168.12.222:63223
[2018-11-19 14:00:13] connect to clients1.google.com:443
[2018-11-19 14:00:13] Socket connected to proxy 192.168.12.222:63223
[2018-11-19 14:00:13] Socket connected to ss server: ss-ip:443
[2018-11-19 14:00:14] Socket connected to ss server: ss-ip:443
[2018-11-19 14:00:14] connect to accounts.google.com:443
[2018-11-19 14:00:14] Socket connected to proxy 192.168.12.222:63223
[2018-11-19 14:00:14] Socket connected to ss server: ss-ip:443
[2018-11-19 14:00:34] connect to www.google.com:80
[2018-11-19 14:00:34] Socket connected to proxy 192.168.12.222:63223
[2018-11-19 14:00:34] Socket connected to ss server: ss-ip:443
[2018-11-19 14:00:43] connect to clients1.google.com:443
[2018-11-19 14:00:43] Socket connected to proxy 192.168.12.222:63223
[2018-11-19 14:00:43] Socket connected to ss server: ss-ip:443
[2018-11-19 14:00:44] connect to clients1.google.com:443
[2018-11-19 14:00:44] Socket connected to proxy 192.168.12.222:63223
[2018-11-19 14:00:44] Socket connected to ss server: ss-ip:443
[2018-11-19 14:01:16] connect to clients1.google.com:443
[2018-11-19 14:01:16] Socket connected to proxy 192.168.12.222:63223
[2018-11-19 14:01:19] Socket connected to ss server: ss-ip:443
[2018-11-19 14:01:19] connect to clients1.google.com:443
[2018-11-19 14:01:19] Socket connected to proxy 192.168.12.222:63223
[2018-11-19 14:01:23] Socket connected to ss server: ss-ip:443
```

**Comment by chenshaoju** [comment]
有可能，请求看起来是正常的，但是也可能是被代理的策略限制了。

**Comment by zhanglc** [comment]
又找到一台代理服务器，使用的是sameersbn/squid ，这个是运行在docker 里面的，现在这台服务器，我们可以改一些配置，做一些测试，但是我这里没有思路了，请教一下，下面如何排查?

**Comment by chenshaoju** [comment]
首先，能Ping通服务器吗？

**Comment by zhanglc** [comment]
> 首先，能Ping通服务器吗？
可以的
--------------------
我在想是不是因为squid不支持socks5代理？
ss 正向代理的处理逻辑是什么 ？

**Comment by chenshaoju** [comment]
当你在某些企业网络中，可能需要通过一个代理服务器才能上网。
如果你是在这种情况下，你才需要设置正向代理。
如果你是直接上网，不需要代理服务器的话，则不需要设置代理服务器。

**Comment by zhanglc** [comment]
这个我明白的。现在的情况是：开发机A通过代理服务器B上的网，所以使用正向代理应该是正确的。

这里的正向代理是使用Http CONNECT  这种方式么？

**Comment by chenshaoju** [comment]
是： https://github.com/shadowsocks/shadowsocks-windows/blob/8ce4b3b8967be1df0409a5992bb9746cbbb155c2/shadowsocks-csharp/Proxy/HttpProxy.cs#L67

**Comment by zhanglc** [comment]
做一下反馈：
1. 目前正向代理可能用了，之前的不能用，不是ss的问题
2. 现在有一个问题，就是访问被墙的网站，要刷新几次才能出来，ss-server 有很多的 connection reset by peer ，这个是有排查或优化的方向么？

**Comment by chenshaoju** [comment]
请尝试更换一个端口看看，比如４４３。

**Comment by AnonymousWebHacker** [comment]
@chenshaoju And in the event that it is an HTTPS squid?
