### ISSUE TITLE
今天一早上都连不上，很奇怪，查看log 异常

### ISSUE THREAD

**Issue by White99** [shadowsocks/shadowsocks-windows#2108]
[2018-12-09 11:40:56] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2018-12-09 11:41:02] connect to clients1.google.com:443

**Comment by chenshaoju** [comment]
这意味着从你的计算机到你的服务器的链接被切断了，请尝试重新启动你的光猫和路由器，然后再试。

如果你的SS服务是购买的，请与你的SS服务商联系或访问SS服务商的网站更新或更换服务器信息。

如果你是自己搭的，请Ping你的服务器，如果能通，请尝试更换一个SS端口看看。

如果Ping也不通，但是从海外能Ping通的话（ https://ping.eu/ping/ ），说明你的服务器可能被墙了，请更换一个IP或新开一个服务器。

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭的，请尝试套一个Simple-obfs或者GoQuite。
