### ISSUE TITLE
Error Occur when launching shadowsocks

### ISSUE THREAD

**Issue by levelyutechblog** [shadowsocks/shadowsocks-windows#2157]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.3.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win7

### Steps you have tried / 操作步骤
launching the shawdowsocks

### What did you expect to see? / 期望的结果
No error 

### What did you see instead? / 实际结果
![image](https://user-images.githubusercontent.com/33856843/51093455-9dda0380-17de-11e9-924b-7484422346c0.png)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
[2019-01-14 09:20:22] System.Net.NetworkInformation.NetworkInformationException (0x80004005): Unknown error (0xc0000001)
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetAllTcpConnections()
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetActiveTcpListeners()
   at Shadowsocks.Controller.Listener.CheckIfPortInUse(Int32 port)
   at Shadowsocks.Controller.Listener.Start(Configuration config)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
```

**Comment by chenshaoju** [comment]
可能和TCP/IP或Winsocks有关，请尝试以管理员身份启动命令提示符或者PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机再看看。如果你的计算机是手动指定IP的，重启后可能需要再手动设置一次。如果是自动分配（DHCP）则无此问题。

重启后看看效果是否有改善。

**Comment by levelyutechblog** [comment]
Now I can launch it without error , but I don't think it works.
[2019-01-14 11:40:28] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
Please make sure your server has usable and connectable.

You can test your server port is connectable at http://tool.chinaz.com/port/

For example, This is not blocked:
![image](https://user-images.githubusercontent.com/515763/51096016-f798f880-17f3-11e9-87d3-9da06740fa1c.png)

This is blocked:
![image](https://user-images.githubusercontent.com/515763/51096020-02ec2400-17f4-11e9-9690-797aaf11326a.png)

If blocked, Please test it at https://www.infobyip.com/tcpportchecker.php (Overseas) .

**Comment by celeron533** [comment]
@levelyutechblog your .net framework may corrupted
