### ISSUE TITLE
Win 10 开启 Hyper-V 后，启动客户端报端口被占用

### ISSUE THREAD

**Issue by joshyao** [shadowsocks/shadowsocks-windows#2181]
### 影梭版本
4.1.3.1

### 使用环境（操作系统，.NET Framework等）
Windows 10 Version 1809 （OS Build 17763.292）

### 操作步骤
添加 `Hyper-V` 组件，启动SS客户端，提示端口被占用  
尝试调整为其他端口，启动仍然提示端口被占用  
通过`netstat -an ` 命令未发现有对应端口被占用
卸载 `Hyper-V` 组件，启动SS客户端，恢复正常

### 日志文件
```
[2019-01-29 14:06:38] System.Exception: Port already in use ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   --- End of inner exception stack trace ---
[2019-01-29 14:06:40] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:1080
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
```

**Comment by studentmain** [comment]
有点意思，Windows Server 2019 Hyper-V能跑

**Comment by joshyao** [comment]
> 有点意思，Windows Server 2019 Hyper-V能跑

嗯，以前也没遇到过这个问题。
重新换用了一个高位端口，现在可以正常启动了。

**Comment by joshyao** [comment]
换用高位端口号后，问题解决！

**Comment by yanshibin** [comment]
遇到同样的问题了,不知道什么原因开启 Hyper-V 后 就会提示端口占用

**Comment by chenshaoju** [comment]
请尝试换一个高位端口看看，比如 10800 。

**Comment by taoweiming** [comment]
Hyper-V占用2181-2279端口，不知道如何解决

**Comment by chenshaoju** [comment]
请尝试在SS的编辑服务器界面的右下角的代理端口换一个端口看看。
