### ISSUE TITLE
Crashes due to bugs in Statistics module

### ISSUE THREAD

**Issue by DeepMediaAdmin** [shadowsocks/shadowsocks-windows#2280]
### Shadowsocks version / 影梭版本
4.1.5.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
* .NET Framework 4.7.2 [Microsoft (R) Build Engine version 4.7.3190.0]
* Windows 10 [Version 10.0.17763.379]

### Steps you have tried / 操作步骤
Enable Statistics, and just let it run for days. And it crashes with "Shadowsocks non-UI Error" pop-up window.

### What did you expect to see? / 期望的结果
No crashes.

### What did you see instead? / 实际结果
SS crashes with a pop-up window.

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

```
---------------------------
Shadowsocks non-UI Error
---------------------------
Unexpected error, shadowsocks will exit. Please report to https://github.com/shadowsocks/shadowsocks-windows/issues 

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)

   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()

   at System.Collections.Generic.List`1.Enumerator.MoveNext()

   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at Shadowsocks.Model.StatisticsRecord..ctor(String identifier, ICollection`1 inboundSpeedRecords, ICollection`1 outboundSpeedRecords, ICollection`1 latencyRecords)

   at Shadowsocks.Controller.AvailabilityStatistics.UpdateRecords()

   at Shadowsocks.Controller.AvailabilityStatistics.Run(Object _)

   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.TimerQueueTimer.CallCallback()

   at System.Threading.TimerQueueTimer.Fire()

   at System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
---------------------------
OK   
---------------------------
```

**Comment by chenshaoju** [comment]
There is a bug in Statistics, Case Shadowsocks crash.

This issue has known, But the part of the code is mostly dead.

For now, please do not enable Statistics.

**Comment by chenshaoju** [comment]
Since there has been no reply for a long time, this Issue has been closed.
