### ISSUE TITLE
time out

### ISSUE THREAD

**Issue by zyanfly** [shadowsocks/shadowsocks-windows#2396]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows7  .NET Framework 4.8

### Steps you have tried / 操作步骤
未做任何认为操作，无法连接

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2019-06-10 15:11:06] connect to api.github.com:443
[2019-06-10 15:11:12] 174.137.55.120:8443 timed out
[2019-06-10 15:11:12] connect to api.github.com:443
[2019-06-10 15:11:17] 174.137.55.120:8443 timed out
[2019-06-10 15:11:17] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
请提供操作系统版本、SS版本、以及SS的日志。

**Comment by zyanfly** [comment]
已经附上报错日志，后面疯狂的timed out

**Comment by chenshaoju** [comment]
你好，经过第三方测试，你的服务器被墙了，你可能需要联系你的VPS服务商更换IP：
![image](https://user-images.githubusercontent.com/515763/59179411-75d7ac00-8b94-11e9-8e40-a10be19efe69.png)

第三方测试地址：https://ipcheck.need.sh/

**Comment by zyanfly** [comment]
十分感谢
