### ISSUE TITLE
配置代理服务器后仍无法访问谷歌

### ISSUE THREAD

**Issue by waliguder** [shadowsocks/shadowsocks-windows#2397]
环境：win10专业版
shadowsocks：4.1.6
代理模式：全局代理

**Comment by chenshaoju** [comment]
请提供SS的日志。

**Comment by waliguder** [comment]
![image](https://user-images.githubusercontent.com/27879437/59180877-97d32d80-8b98-11e9-83f9-6de6fb9583f7.png)

**Comment by waliguder** [comment]
@chenshaoju

**Comment by chenshaoju** [comment]
你好，经过第三方测试( https://ipcheck.need.sh/ )，你的服务器被墙了：
![image](https://user-images.githubusercontent.com/515763/59181330-ab32c880-8b99-11e9-97b8-8b737f7c0040.png)

请尝试联系你的VPS服务商更换一个IP看看。如果可能，请在更换IP后套一个插件，被封概率会降低：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by waliguder** [comment]
那为什么另一个人还能用这个梯子。。。是他给我的，这个会绑定设备么？ @chenshaoju

**Comment by chenshaoju** [comment]
这个……你最好确认一下他目前用的还是这个IP。

**Comment by flypigeon** [comment]
@chenshaoju 请问大神，我配置之后，也是一样访问不了
in 0kb out 67.8k
[2019-06-10 17:18:14] connect to clients1.google.com:443
[2019-06-10 17:18:15] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-06-10 17:18:15] connect to clients1.google.com:443
[2019-06-10 17:18:17] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-06-10 17:18:29] connect to clients1.google.com:443
[2019-06-10 17:18:31] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-06-10 17:18:31] connect to clients1.google.com:443
[2019-06-10 17:18:32] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
`由于目标计算机积极拒绝，无法连接。` - 这看起来要么被墙了，要么你的服务器配置有误（IP、端口、加密方式或者密码不对），请先测试一下你的服务器在国内是否能正常访问： https://ipcheck.need.sh/

**Comment by flypigeon** [comment]
使用ipcheck 都属于正常，刚换了ip

**Comment by chenshaoju** [comment]
你换了IP后，服务端配置文件里的IP换了吗？

**Comment by channingy** [comment]
@chenshaoju 请问大神，同样错误：
![image](https://user-images.githubusercontent.com/36360567/59973261-ff916b80-95cf-11e9-9525-31570e458ea3.png)

用这个 https://ipcheck.need.sh/ 工具测试过，通的。
测试过手机是可以科学上网，但是win10 PC总是不行。请问还有哪些地方需要检查的？谢谢。

**Comment by chenshaoju** [comment]
日志后面被截掉了，能否复制一下？

**Comment by zexus** [comment]
> 日志后面被截掉了，能否复制一下？
@chenshaoju 
你好，同樣出現類似問題，手機能用，windows出現問題
用这个 https://ipcheck.need.sh/ 工具测试101.78.248.151通過
[2019-06-24 17:50:06] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:06] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:06] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:06] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:06] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:09] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:11] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:14] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:24] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:27] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:29] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:29] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:32] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:34] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:34] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:34] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-06-24 17:50:39] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:39] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:44] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:50:56] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:00] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:01] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:03] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:04] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:05] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:06] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:07] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:08] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:09] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:11] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:12] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:14] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:19] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:19] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:21] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:22] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:23] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:24] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:24] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:26] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:27] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:28] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:28] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:29] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:30] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:33] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:34] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:36] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:38] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:40] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:41] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:43] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:45] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:45] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:46] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:47] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:48] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:50] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:51] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:51] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:52] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:53] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:53] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:51:53] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:58:50] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:58:54] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:58:55] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:59:01] hk.c.cloudss.win:17475 timed out
[2019-06-24 17:59:08] hk.c.cloudss.win:17475 timed out
[2019-06-24 18:00:26] hk.c.cloudss.win:17475 timed out
[2019-06-24 18:00:31] hk.c.cloudss.win:17475 timed out
[2019-06-24 18:00:36] hk.c.cloudss.win:17475 timed out

**Comment by chenshaoju** [comment]
你的服务器的确能通，但是提示超时可能意味着你的服务器无法从你的当前网络访问。

请尝试使用这个第三方的小工具进行测试，出现问题的时候看看是否能通：https://github.com/chenshaoju/tcpportcheck

**Comment by channingy** [comment]
> 日志后面被截掉了，能否复制一下？

`[2019-06-22 13:06:23] os suspend
[2019-06-22 13:07:25] os wake up
[2019-06-22 13:07:35] Shadowsocks started (4.1.6)
[2019-06-22 13:07:35] controller started
[2019-06-22 13:07:41] IP:PORT timed out
[2019-06-22 13:07:41] IP:PORT timed out
[2019-06-22 13:07:41] IP:PORT timed out
[2019-06-23 15:50:30] Shadowsocks started (4.1.6)
[2019-06-23 15:50:34] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-06-23 15:57:47] Shadowsocks started (4.1.6)
[2019-06-23 15:57:53] Shadowsocks started (4.1.6)
[2019-06-26 20:55:46] Shadowsocks started (4.1.6)
[2019-06-26 20:55:50] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)`
@chenshaoju 截图上传不了，只有把log粘出来了。tcpportcheck工具试过，是通的。

**Comment by chenshaoju** [comment]
你的服务器是自己搭的吗？如果是，请尝试换一个端口或者加密算法，如果可能，请尝试套一个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by celeron533** [comment]
手机和PC连在同一个宽带网络上吗？
如果手机在其他网络，可以尝试让PC通过手机网络来测试。

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。

**Comment by 0754** [comment]
@chenshaoju 请问大神，日志一直是这两句话是什么原因
connect to clients1.google.com:443 
xxxxx  time out
（xxxxx 是服务器IP和端口）

**Comment by chenshaoju** [comment]
请尝试使用这个第三方的工具测试你的服务器的连通性：http://ip100.info/check
