### ISSUE TITLE
Global Mode doesnt work anymore on Windows

### ISSUE THREAD

**Issue by marvinb8930** [shadowsocks/shadowsocks-windows#2444]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
Shadowsocks-4.1.5 and Shadowsocks-4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 Pro
Version	10.0.17134 Build 17134

### Steps you have tried / 操作步骤
I deleted all the config files, restarted my shadowsocks on my virtual server, tried out 4.1.6 and 4.1.5. 

### What did you expect to see? / 期望的结果
Global mode is working on my android. If I use shadowsocks on android and check my IP I have the expected server IP, but on Windows it doesnt work anymore. 

### What did you see instead? / 实际结果
Shadowsocks works, but as soon as I change to Mode-Global, I am not online anymore.

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

[2019-07-05 19:52:55] Shadowsocks started (4.1.6)
[2019-07-05 19:54:07] Shadowsocks started (4.1.6)
[2019-07-05 19:54:18] Shadowsocks started (4.1.6)
[2019-07-05 19:54:18] Shadowsocks started (4.1.6)
[2019-07-05 19:54:23] Checking GFWList from https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
[2019-07-05 19:54:38] xxx.xx.xxx.xx:xxxx timed out
[2019-07-05 19:54:43] xxx.xx.xxx.xx:xxxx timed out
[2019-07-05 19:54:46] xxx.xx.xxx.xx:xxxx timed out
[2019-07-05 19:54:46] xxx.xx.xxx.xx:xxxx timed out
[2019-07-05 19:54:46] xxx.xx.xxx.xx:xxxx timed out
[2019-07-05 19:54:46] xxx.xx.xxx.xx:xxxx timed out
[2019-07-05 19:54:46] xxx.xx.xxx.xx:xxxx timed out
[2019-07-05 19:54:46] xxx.xx.xxx.xx:xxxx timed out
[2019-07-05 19:54:46] xxx.xx.xxx.xx:xxxx timed out
[2019-07-05 19:54:47] xxx.xx.xxx.xx:xxxx timed out
[2019-07-05 19:54:47] xxx.xx.xxx.xx:xxxx timed out
[2019-07-05 19:54:47] xxx.xx.xxx.xx:xxxx timed out
[2019-07-05 19:55:04] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-07-05 19:55:04] Shadowsocks started (4.1.6)
[2019-07-05 19:55:04] Shadowsocks started (4.1.6)
[2019-07-05 19:55:24] Shadowsocks started (4.1.6)
[2019-07-05 19:55:24] Shadowsocks started (4.1.6)
[2019-07-05 19:55:24] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-07-05 19:55:41] Shadowsocks started (4.1.6)
[2019-07-05 21:57:27] Shadowsocks started (4.1.6)
[2019-07-05 21:57:31] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-07-05 21:57:31] Shadowsocks started (4.1.6)
[2019-07-05 21:57:32] Shadowsocks started (4.1.6)
[2019-07-05 21:57:51] Checking GFWList from https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
[2019-07-05 21:57:52] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-07-05 21:58:14] Shadowsocks started (4.1.6)
[2019-07-05 21:58:15] Shadowsocks started (4.1.6)
[2019-07-05 21:58:24] Shadowsocks started (4.1.6)
[2019-07-05 21:58:24] Shadowsocks started (4.1.6)
[2019-07-05 22:08:32] Shadowsocks started (4.1.6)
[2019-07-05 22:08:36] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-07-05 22:08:40] HA switching to server: 144.34.254.56:2180
[2019-07-05 22:08:40] Shadowsocks started (4.1.6)
[2019-07-05 22:08:44] Shadowsocks started (4.1.6)
[2019-07-05 22:10:00] Shadowsocks started (4.1.6)
[2019-07-05 22:28:44] Shadowsocks started (4.1.6)
[2019-07-05 22:28:48] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-07-05 22:28:57] Shadowsocks started (4.1.6)
[2019-07-05 22:28:57] Shadowsocks started (4.1.6)

**Comment by chenshaoju** [comment]
This looks like your server has been blocked or inaccessible. Please use this 3rd-party tool to test your server: https://ipcheck.need.sh/

**Comment by klaaktu** [comment]
@chenshaoju There is some bullshit in win10 1903. Proxy works because I can access blocked sites, but it seems that the website knows my location even tho I'm using global in windows and browser. e.g. https://international.download.nvidia.com/Windows/431.18hf/431.18-desktop-notebook-win10-64bit-international-dch.hf.exe on 1802 everything is fine, on 1903 it redirect me to nvidia.cn which is fast at first but soon drops to low or no speed at all. Is there a way to solve this?

**Comment by chenshaoju** [comment]
I tested, Looks fine:
![2019-07-06](https://user-images.githubusercontent.com/515763/60753703-530cac00-a009-11e9-9121-d8b1ea14ea02.png)

If you open https://ip.cn ,The IP address is your public IP or Proxy server IP?

**Comment by marvinb8930** [comment]
But as I said, it works fine on my Android, same server, same settings.
Anyway, I checked it as you said and it looks fine to me (even though I can only read half of the Chinese):

![check](https://user-images.githubusercontent.com/48605708/60753774-1aa0aa00-9fd8-11e9-938c-1aeb584b9a25.png)

**Comment by marvinb8930** [comment]
I checked and even though I can only read half of the Chinese, it looks fine to me.
Also, it work on my Android phone, same server, same settings.

![check](https://user-images.githubusercontent.com/48605708/60753793-550a4700-9fd8-11e9-96c4-24741da964b3.png)

**Comment by chenshaoju** [comment]
Please try reset TCP/IP and Winsocks by running these command at Administrator PowerShell or cmd.exe :
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```

**Comment by klaaktu** [comment]
@chenshaoju Proxy server ip. Browsing website is fine but when I download from nvidia it redirects to cn url, as shown in chrome's download tab.
![image](https://user-images.githubusercontent.com/52594481/60753812-b5dd5380-9fc7-11e9-9a91-b320ad31b8f3.png)
I have cleared dns cache in windows and chrome, the remote dns used by shadowsocks is google and cloudflare dns.

**Comment by marvinb8930** [comment]
> Please try reset TCP/IP and Winsocks by running these command at Administrator PowerShell or cmd.exe :
> 
> ```
> netsh interface ipv4 reset
> netsh interface ipv6 reset
> netsh interface tcp reset
> netsh winsock reset
> ```

No change. If I use global mode I am basically offline.

**Comment by chenshaoju** [comment]
@klaaktu This looks like your connect has been cut.
If your server is built by yourself, Please try using a plugin: https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

@marvinb8930 Please make a test: Tune off or exit Shadowsocks.exe ,goto https://ip.cn, write current public IP, And reboot your router and fiber optic modem ( if have).
After Internet back on-line, refresh your browser ( https://ip.cn ), If IP address is changed, Then start shadowsocks.exe test again.

**Comment by NAVras-Z** [comment]
@chenshaoju I canceled it after seeing .cn url. ( If you mean the slowing down problem, then yea I'm using the latest plugin. I guess it's just my vps provider being too popular with gfw. )
I tried the url on edge browser, and it shows .com instead of .cn when downloading. So... chrome is probably broken by the 1902 update. Thx for the reply tho.

**Comment by klaaktu** [comment]
@chenshaoju I canceled it after seeing the .cn url. ( If u mean the slowing down problem instead, yea I'm using the latest plugin. I guess it's just my vps provider being too popular with gfw. )
I tried the url on Edge browser, and it shows .com instead of .cn when downloading. So chrome is probably broken by the 1902 update... Thx for the reply tho.

**Comment by chenshaoju** [comment]
Hmmm, Odd,Can you try Firefox?

**Comment by klaaktu** [comment]
@chenshaoju I figured out what's wrong after Firefox finished installing xD
I upgraded the second pc to 1903 as well, and then found that it does not have this problem... sry microsoft.
So I remembered to press f12 before download, and under network tab saw "status: 301(from disk)" with the cached Nvidia address and IP being the .cn version. I have no idea when or how I got it and why it persists after nearly a dozen retry. But after clearing Chrome's cache I can now get .com address through proxy no problem.

**Comment by marvinb8930** [comment]
@chenshaoju 
I tried that but nothing works. I even switched to hot spot from my iPhone but again as soon as I change to global mode I am offline. But, during the week I use it on my phone and it works perfectly so my virtual server shouldnt be the problem I guess?
BTW Thanks for the suppoer so far, I appreciate it!!!

**Comment by marvinb8930** [comment]
My problem still exists...it only works on my phone, no need to close it yet..

**Comment by chenshaoju** [comment]
I guess is your ISP Blocked your server...
Did you try to some public wifi hotspot like Starbucks or McDonald?

**Comment by marvinb8930** [comment]
I tried my own hotspot.
For example. 
OnePlus mobile internet + VPN Android app = works fine.
OnePlus mobile internet hotspot + Windows PC WIFI = works fine
OnePlus mobile internet hotsopt + Windows PC Wifi + ShadowSocks 4.1.6 Global Mode = not working

**Comment by chenshaoju** [comment]
In Global mode, There is any log output?

**Comment by marvinb8930** [comment]
There is. I did this:
I started shadowsocks 4.1.5, System Proxy NOT enabled, use the internet, works.
Then I change to System Proxy Enabled, PAC Mode, internet works, but have the same IP address.
Then I change to Global mode, then I am offline.

I attached the full log of this!
[logfile.txt](https://github.com/shadowsocks/shadowsocks-windows/files/3389712/logfile.txt)

**Comment by chenshaoju** [comment]
From the log, It looks your server is inaccessible from your network.
But it can work at PAC mode, This is odd.
Did you have Firefox? If have, Please try set a proxy manually:
![image](https://user-images.githubusercontent.com/515763/61182715-cb0e4e00-a669-11e9-9d9f-a28ba2f5dc7f.png)

*Change 10800 if your shadowsocks local proxy port is 1080

**Comment by marvinb8930** [comment]
I migrated the server to a new destination, reinstalled Ubuntu, reinstalled Shadowsocks and now it works fine again on both, my computer and my phone. Don't really understand why, but it works now so all good!
Thanks so much for your support!!
多谢！
