### ISSUE TITLE
Shadowsocks Error: Port already in use 1080

### ISSUE THREAD

**Issue by abirmoy** [shadowsocks/shadowsocks-windows#2449]
### Shadowsocks version / 影梭版本
4.1.6.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 pro (just updated toversion 1809), .NET3.5, 4.7

### Steps you have tried / 操作步骤
System proxy>Global/pack/disable(no error is there)
in order to solve:
1.  Internet properties>LAN setting> enable/disable stuffs
2.
reset TCP/IP and Winsocks by running these command at Administrator PowerShell or cmd.exe :

netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
### What did you expect to see? / 期望的结果
No error

### What did you see instead? / 实际结果
Shadowsocks Error: Port already in use 1080
![Capture](https://user-images.githubusercontent.com/50194655/60974488-bde91a80-a35c-11e9-9b26-db7ea4dc1cc5.PNG)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   --- End of inner exception stack trace ---
[2019-07-10 22:18:28] [Error] System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
[2019-07-10 22:18:28] [Error] System.Exception: Port already in use 0 ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   --- End of inner exception stack trace ---
[2019-07-10 22:18:55] [Error] System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
[2019-07-10 22:18:55] [Error] System.Exception: Port already in use 1080 ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   --- End of inner exception stack trace ---
[2019-07-10 22:18:57] [Error] System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
[2019-07-10 22:18:57] [Error] System.Exception: Port already in use 0 ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   --- End of inner exception stack trace ---
[2019-07-10 22:19:31] [Error] System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
[2019-07-10 22:19:31] [Error] System.Exception: Port already in use 1080 ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   --- End of inner exception stack trace ---
[2019-07-10 22:19:32] [Error] System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
[2019-07-10 22:19:32] [Error] System.Exception: Port already in use 0 ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   --- End of inner exception stack trace ---
[2019-07-10 22:19:44] [Error] System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
[2019-07-10 22:19:44] [Error] System.Exception: Port already in use 1080 ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   --- End of inner exception stack trace ---
[2019-07-10 22:19:46] [Error] System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
[2019-07-10 22:19:46] [Error] System.Exception: Port already in use 0 ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   --- End of inner exception stack trace ---
[2019-07-10 22:20:10] [Error] System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
[2019-07-10 22:20:10] [Error] System.Exception: Port already in use 1080 ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   --- End of inner exception stack trace ---

**Comment by celeron533** [comment]
please change the local listening port

**Comment by ahmadalli** [comment]
for me it related to hyper-v for some reason. If I disabled hyper-v it was ok to use port 1080. Since I needed hyper-v, I switched to another port at the end

**Comment by abirmoy** [comment]
> for me it related to hyper-v for some reason. If I disabled hyper-v it was ok to use port 1080. Since I needed hyper-v, I switched to another port at the end
I think it is caused by hyper-v, because the issue appeared after enabling hyper-v.
However I solved it by by editing gui-config.json file. I changed the local port to 2080
and now it working perfectly.

**Comment by celeron533** [comment]
You have no need to edit the config file directly. You can do it on the server editing form.
