### ISSUE TITLE
windows7 无法正常使用

### ISSUE THREAD

**Issue by mtwoz** [shadowsocks/shadowsocks-windows#2456]
### Shadowsocks version / 影梭版本
4.1.7

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows 7
.NET Framework 4.7+

### Steps you have tried / 操作步骤
正常使用

### What did you expect to see? / 期望的结果
翻墙

### What did you see instead? / 实际结果
[2019-07-13 17:31:34] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-07-13 17:31:34] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-07-13 17:31:34] Shadowsocks started (4.1.7)
[2019-07-13 17:31:34] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-13 17:31:37] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-13 17:49:23] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-13 17:49:24] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-13 17:52:09] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).

**Comment by chenshaoju** [comment]
`由于目标计算机积极拒绝，无法连接。`  这看起来很像你的服务器没有正常工作，可能防火墙配置错误或者SS服务端的服务没有启动。
请使用第三方的服务检测你的服务器从国内的连通性：https://ipcheck.need.sh/
请使用第三方的应用在有问题的计算机上检测连通性：https://github.com/chenshaoju/tcpportcheck/

**Comment by Wangbin9019** [comment]
我也是win7，同样的上述问题，已经测试服务器国内连通性正常，也测试了第三方应用在计算机的连通性正常，但手机和电脑都不能上google，shadowsocks 4.1.7

**Comment by Wangbin9019** [comment]
Shadowsocks version / 影梭版本

4.1.7

Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

windows 7
 .NET Framework 4.7+

Steps you have tried / 操作步骤

正常使用

What did you expect to see? / 期望的结果

翻墙
实际[2019-07-17 09:14:01] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-17 09:14:03] connect to api.github.com:443
[2019-07-17 09:14:04] System.Net.Sockets.SocketException (0x80004005): A socket operation was attempted to an unreachable network
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-07-17 09:14:04] connect to api.github.com:443
[2019-07-17 09:14:04] System.Net.Sockets.SocketException (0x80004005): A socket operation was attempted to an unreachable network
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-07-17 09:14:04] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-07-17 09:15:45] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-17 09:15:45] Shadowsocks started (4.1.7.1)
[2019-07-17 09:16:04] Shadowsocks started (4.1.7.1)
[2019-07-17 09:16:04] Shadowsocks started (4.1.7.1)
[2019-07-17 09:16:41] Shadowsocks started (4.1.7.1)
[2019-07-17 09:16:41] 运行日志：

**Comment by chenshaoju** [comment]
请尝试Ping你的服务器，能通吗？

**Comment by Wangbin9019** [comment]
能啊，国内国外的ICMP TCP都是绿色对勾

**Comment by chenshaoju** [comment]
请尝试右击托盘区的纸飞机图标，选择PAC，再点击从GFWList更新本地PAC，是否提示成功或者失败？出现提示后，日志中有任何新增的内容显示出来吗？

**Comment by Wangbin9019** [comment]
> 请尝试右击托盘区的纸飞机图标，选择PAC，再点击从GFWList更新本地PAC，是否提示成功或者失败？出现提示后，日志中有任何新增的内容显示出来吗？

我点击从GFWList更新本地PAC后，显示failed to update PAC  file. 日志如下：
[2019-07-17 20:25:08] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-17 20:25:19] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-17 20:25:19] Checking GFWList from https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
[2019-07-17 20:25:19] connect to raw.githubusercontent.com:443
[2019-07-17 20:25:19] Socket connected to ss server: 149.28.198.253:22
[2019-07-17 20:25:20] connect to raw.githubusercontent.com:443
[2019-07-17 20:25:20] Socket connected to ss server: 149.28.198.253:22
[2019-07-17 20:25:20] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
你在尝试访问你的服务器的22端口？

这个端口默认是SSH，你确认你的SS服务位于22端口上吗？

**Comment by Wangbin9019** [comment]
> 你在尝试访问你的服务器的22端口？
> 
> 这个端口默认是SSH，你确认你的SS服务位于22端口上吗？

我使用的下面链接的教程，使用PuTTY，
[https://kylindc.github.io/post/63883/#SSR%E5%AE%A2%E6%88%B7%E7%AB%AF%E9%85%8D%E7%BD%AE](url)
![Capture](https://user-images.githubusercontent.com/52819545/61388019-cd7edb00-a8e9-11e9-8462-2ea0d42daa6c.JPG)

**Comment by chenshaoju** [comment]
请仔细阅读教程，教程本身没问题，你的配置过程有问题。

**Comment by Wangbin9019** [comment]
> 请仔细阅读教程，教程本身没问题，你的配置过程有问题。

那我是否得重新配置一下，重新配置，教程里的服务器配置模板，我是完全照抄的，除了注释部分，所以是否需要修改哪些地方

**Comment by chenshaoju** [comment]
你开始就错了，你应该连接你的SS服务端的端口，而不是你的VPS的SSH端口。

**Comment by Wangbin9019** [comment]
> 你开始就错了，你应该在SS客户端（不是Putty）里连接你的SS服务端的端口，而不是你的VPS的SSH端口。

大神，我比较机械，教程里流程：1，购买服务器 2，使用Putty配置服务器 3安装SS客户端（就是飞机图标），4 在客户端填上IP地址和端口号，密码。
您说我开始错了，我还是不懂，不好意思，是第一步购买服务器哪错了？好急啊

**Comment by Wangbin9019** [comment]
我修改了，客户端填的不应该是SSH的端口，而是搭建服务器时，我自己定义的端口，但我修改后反而显示连接不上，Time out，反复试了几个端口都连接不上。是因为这些端口别人先用了吗？发自我的华为手机-------- 原始邮件 --------主题：Re: [shadowsocks/shadowsocks-windows] windows7 无法正常使用 (#2456)发件人：Chen Shaoju 收件人：shadowsocks/shadowsocks-windows 抄送：Wangbin9019 ,Comment 你开始就错了，你应该连接你的SS服务端的端口，而不是你的VPS的SSH端口。

**Comment by chenshaoju** [comment]
你的服务器上的SS服务安装后修改了配置文件吗？

修改后SS服务启动了吗？

**Comment by Wangbin9019** [comment]
这些端口和密码我都试过，都是time out 发自我的华为手机-------- 原始邮件 --------主题：Re: [shadowsocks/shadowsocks-windows] windows7 无法正常使用 (#2456)发件人：Chen Shaoju 收件人：shadowsocks/shadowsocks-windows 抄送：Wangbin9019 ,Comment 你的服务器上的SS服务安装后修改了配置文件吗？

修改后SS服务启动了吗？

**Comment by chenshaoju** [comment]
请检查你的服务器上的ss服务是否启动了。

如果确定启动了，请检查配置文件的端口是否正确。

如果端口无误，请检查服务器上是否有网络防火墙（如：iptables或ufw等）。

**Comment by Wangbin9019** [comment]
![1](https://user-images.githubusercontent.com/52819545/61457101-2e65ec00-a99a-11e9-8a0a-9943f8b0906b.JPG)
![2](https://user-images.githubusercontent.com/52819545/61457113-33c33680-a99a-11e9-9325-d069376935d8.JPG)
我使用多站点ping服务器，很多都可以
![3](https://user-images.githubusercontent.com/52819545/61457322-a6ccad00-a99a-11e9-91ba-d2c8010bac00.JPG)
图片3除了Ping SSH的22端口可以外，其他我配置的端口都不行

**Comment by Wangbin9019** [comment]
> 请检查你的服务器上的ss服务是否启动了。
> 
> 如果确定启动了，请检查配置文件的端口是否正确。
> 
> 如果端口无误，请检查服务器上是否有网络防火墙（如：iptables或ufw等）。

刚才图片不知道传上去没，第一张是服务器防火墙截图，没有防火墙。
第二张图片是服务器截图，不知道怎么才算服务器启用。
第三张是使用多站点pin端口，都不行，除了SSH的22端口

**Comment by Wangbin9019** [comment]
> 请检查你的服务器上的ss服务是否启动了。
> 
> 如果确定启动了，请检查配置文件的端口是否正确。
> 
> 如果端口无误，请检查服务器上是否有网络防火墙（如：iptables或ufw等）。

![4](https://user-images.githubusercontent.com/52819545/61457662-69b4ea80-a99b-11e9-8a35-27f3638a4842.JPG)

**Comment by chenshaoju** [comment]
防火墙是指操作系统的防火墙，不是你的VPS服务商提供的防火墙。

是这样的，我没有办法帮一步步的教你如何搭建，我强烈建议你仔细阅读教程，或者换一个教程重来一次。

**Comment by gaorui84** [comment]
看下你的VPS操作系统装的是什么，如果CentOS7的话Linux一般来说需要设置firewalld（iptables前端），甚至还有可能需要设置SELinux。建议初学者用Debian或者Ubuntu。

**Comment by Wangbin9019** [comment]
我昨天重装了下VPS，但这次我配置服务器用的Xshell，电脑就可以上Google了，但手机依然不行。发自我的华为手机-------- 原始邮件 --------主题：Re: [shadowsocks/shadowsocks-windows] windows7 无法正常使用 (#2456)发件人：gaorui84 收件人：shadowsocks/shadowsocks-windows 抄送：Wangbin9019 ,Comment 看下你的VPS操作系统装的是什么，如果CentOS7的话Linux一般来说需要设置firewalld（iptables前端），甚至还有可能需要设置SELinux。建议初学者用Debian或者Ubuntu。

**Comment by gaorui84** [comment]
这个跟用的ssh客户端软件没关系，是你Linux设置的问题，建议先自学一下Linux基础操作。另外用HW手机就不要fq了吧，别忘了去年除夕HW的人想要发个twitter都要用iPhone才行~~~~
