### ISSUE TITLE
System.Exception: Port 1089 is reserved by system

### ISSUE THREAD

**Issue by malikshi** [shadowsocks/shadowsocks-windows#2474]
> [2019-07-18 19:28:41] System.Exception: Port 1089 is reserved by system ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   --- End of inner exception stack trace ---

windows 10 pro
64 bit
installed
.net 3.5
.net 4.7
.net 4.8

before update new release 1.7.0 is normal but after 1.7.1 got error like that above, so i am tried to use old version again its become error with same issue

**Comment by malikshi** [comment]
solved am i using proxifier SysSettings64.exe and SysSettings32.exe to reset but its same as using cmd command
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
