### ISSUE TITLE
改为PPPOE拨号上网后，手机正常，win10无法连接

### ISSUE THREAD

**Issue by Boneee** [shadowsocks/shadowsocks-windows#2478]
**### Shadowsocks version / 影梭版本**
4.0.9和4.1.7  都不行

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 .NET Framework 4.7.2

**### Steps you have tried / 操作步骤**
在搬家后换成pppoe拨号就无法连接了；
服务器没有被墙；
朋友的windows连接一切正常；
手机连接一切正常；
偶然在IE打开过一次youtube，之后一直不行

**### What did you expect to see? / 期望的结果**
在windows正常使用

**### What did you see instead? / 实际结果**
无法连接

**### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）**
[2019-07-20 10:22:14] System.Net.Sockets.SocketException (0x80004005): 向一个无法连接的网络尝试了一个套接字操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-07-20 10:22:14] System.Net.Sockets.SocketException (0x80004005): 向一个无法连接的网络尝试了一个套接字操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-07-20 10:22:14] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-07-20 10:43:06] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---

**Comment by chenshaoju** [comment]
```向一个无法连接的网络尝试了一个套接字操作``` 请尝试Ping你的服务器，能通吗？

如果能通，请以管理员权限启动PowerShell或命令提示符，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，三行执行完毕后重启计算机看看。

**Comment by Boneee** [comment]
> `向一个无法连接的网络尝试了一个套接字操作` 请尝试Ping你的服务器，能通吗？
> 
> 如果能通，请以管理员权限启动PowerShell或命令提示符，然后执行：
> 
> ```
> netsh interface ipv4 reset
> netsh interface ipv6 reset
> netsh interface tcp reset
> netsh winsock reset
> ```
> 
> 一行一回车，三行执行完毕后重启计算机看看。

能ping通，
重启完还是不行

**Comment by Boneee** [comment]
> `向一个无法连接的网络尝试了一个套接字操作` 请尝试Ping你的服务器，能通吗？
> 
> 如果能通，请以管理员权限启动PowerShell或命令提示符，然后执行：
> 
> ```
> netsh interface ipv4 reset
> netsh interface ipv6 reset
> netsh interface tcp reset
> netsh winsock reset
> ```
> 
> 一行一回车，三行执行完毕后重启计算机看看。

能ping通，
重启完还是不行

**Comment by chenshaoju** [comment]
日志中是否还有 `向一个无法连接的网络尝试了一个套接字操作` 这个提示？

如果没有了，但是仍然有`从传输流收到意外的 EOF 或 0 个字节`的话，你的服务器是自己搭建的还是购买（租用）的？

如果是自己搭建的，请尝试套一个插件看看？https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by Boneee** [comment]
搞完之后日志不更新了= =
是自己搭的，我试试插件

**Comment by chenshaoju** [comment]
请尝试将系统代理切换到PAC模式，然后再从PAC菜单里从GFWList更新本地PAC看看？

**Comment by cbank8** [comment]
我有类似的问题，不过我不是PPPoE，而是笔记本电脑自带的LTE 4G。用wifi没问题，切换到LTE就不行了

[2019-08-03 23:55:03] Shadowsocks started (4.1.7.1)
[2019-08-03 23:55:38] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by cbank8** [comment]
[2019-08-03 23:57:56] System.Net.Sockets.SocketException (0x80004005): A socket operation was attempted to an unreachable network
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Util.Sockets.WrappedSocket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.PipeRemoteReceiveCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
请尝试Ping你的IP地址，能通吗？

如果能，请检查一下你的系统防火墙。

**Comment by cbank8** [comment]
很痛苦，用电脑LTE 4G就是连不上，下面提示里所说的"unreachable network"是指google.com，还是指连不上远程的代理服务器？同样的代理服务器，我付费买的，测了两家不同的10几个服务器，用不同网络是这样的结果(手机用的shadowrocket，PC用的shadow socks)：

1. 联通，PC公司wifi：正常
2. 联通，PC家里宽带wifi：正常
3. 联通，iphone LTE 4G：没测过
4. 移动，iphone LTE 4G：不能用
5. 联通4G，开热点wifi给PC用：正常 
6. 移动4G，开热点wifi给PC用：不能用
7. 联通4G，用PC自带LTE 4G：不能用

求解决办法


[2019-08-20 12:15:26] System.Net.Sockets.SocketException (0x80004005): A socket operation was attempted to an unreachable network
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Util.Sockets.WrappedSocket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.PipeRemoteReceiveCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
你一直没回答这个问题：

在有问题的网络下，Ping你的服务器，能通吗？在没问题的网络下Ping呢？

**Comment by cbank8** [comment]
感谢回复啊，Ping都是通的，你之前让我检查防火墙：
1.我试过关闭防火墙没用
2.不能用的情境下，也不是100%不能用，偶尔是可以用的，比如昨天有一个服务器能用，但今天就不能用了，或者一个服务器打开了google但过几分钟就不能用了，应该不是防火墙问题
3.如果切换到wifi，在同一个笔记本电脑上，没有改动任何设置，就可以用了；LTE和wifi在windows都是设置为public
4.我用了just my socks和加速度共12个服务器，基本上在公司和家里的联通宽带wifi里，12个里10-12个能用，无论是手机还是PC；切换到移动的LTE直连，c18s4和c18s5有时候在手机上能用，大部分时候不能用，PC上我就测试过一两次不能用；切换到联通LTE直连，手机没有测试，PC上大部分时间不能用

我怀疑:1.移动基本被GFW给捕捉到了；2.走LTE 4G，就被GFW给捕捉到了，LTE和wifi对于GFW来说有什么本质不同么？

**Comment by chenshaoju** [comment]
移动的网络存在某些奇怪的封锁或过滤，这个问题已知，且无解，可搜索“移动 墙中墙”或“移动 墙内墙”。

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
