### ISSUE TITLE
请问这是什么征兆？

### ISSUE THREAD

**Issue by 2427237507** [shadowsocks/shadowsocks-windows#2503]
Ping正常，111ms
然而
Ping statistics for xxx:443
     654 probes sent.
     429 successful, 225 failed.  (34.40% fail)
Approximate trip times in milli-seconds (successful connections only):
     Minimum = 66.623ms, Maximum = 1210.033ms, Average = 150.622ms
在TCP请求发送中，经常就是75%的丢包（里面的结果有问题）
SS日志也一直提示Time out
System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-08-11 17:20:50] Shadowsocks started (4.1.7.1)
[2019-08-11 17:25:31] Shadowsocks started (4.1.7.1)
说端口被墙把，又好像不是

**Comment by chenshaoju** [comment]
可能是线路不好。。。你的网络可能刻意优化了ICMP（Ping），导致出现Ping正常，但是TCP连接不稳定的现象。

如果可能，请尝试换一个地区的机房看看。

**Comment by lweo** [comment]
我手机端也是这样，能ping 通但没网！今天下午开始的？莫非ss 完全被 gfw 攻破了？

**Comment by chenshaoju** [comment]
请尝试套一个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by 2427237507** [comment]
> 
> 
> 可能是线路不好。。。你的网络可能刻意优化了ICMP（Ping），导致出现Ping正常，但是TCP连接不稳定的现象。
> 
> 如果可能，请尝试换一个地区的机房看看。

Vultr的日本，机房走移动骨干回
感觉是被干扰之类的，不过这种现象只是持续了1个小时，1个小时后就好了（不是高峰期呀）
我这TCP延迟是小于ICMP延迟（晚上依然保持110ms，ICMP就160+）
我之前试过伪装TLS，但后来发现有点麻烦就不弄了
不过伪装后网速也有500kb一秒（不带任何加速器）
