### ISSUE TITLE
win10升级到build 17134.950后无法使用

### ISSUE THREAD

**Issue by yanyan33333** [shadowsocks/shadowsocks-windows#2513]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 build 17134.950 
.Net v4.0.30319

### Steps you have tried / 操作步骤
打开之后无法使用
在系统升级之前可以正常使用

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
Cannot get Windows 10 system theme mode, return default value 0 (dark mode).

此前可以正常使用的时候没有出现这个log

**Comment by chenshaoju** [comment]
` Cannot get Windows 10 system theme mode, return default value 0 (dark mode). ` 这个问题不是引发无法使用的问题，且会在下一个版本修正。

请问“无法使用”具体表现在什么地方？
请先确保已经更新到最新的PAC（PAC->从GFWList更新本地PAC），系统代理工作在PAC模式下。

**Comment by yanyan33333** [comment]
我使用的是chrome + switchomega,本地代理端口已经打开，但是请求端口的时候没有任何反应，也没有日志
另，我开启了check for updates at startup的时候，每次启动都会检查更新，有如下log
System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 127.0.0.1:7155
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
1.请检查你的网络防火墙（比如Windows自带的），如果可能，请暂时关闭，重启SS后再试。
2.请在SS编辑服务器界面右下角的代理端口选项中换一个高位端口，比如10800，确定后再试。
3.请确保没有启用正向代理：
![image](https://user-images.githubusercontent.com/515763/63227580-818dc180-c21a-11e9-9eda-8095054a8976.png)

**Comment by yanyan33333** [comment]
@chenshaoju 谢谢，已经找到问题，原因是win10升级之后会自动把系统的防火墙打开，导致127.0.0.1都ping 不通。。。。之前升级之前一直关防火墙的，不知道为什么抽风会自动打开。。。把系统防火墙关了就可以了，之前也遇到过这样的情况。。。
感谢感谢
