### ISSUE TITLE
win10 ss碰到无法正常使用的问题

### ISSUE THREAD

**Issue by zzfnuaa** [shadowsocks/shadowsocks-windows#255]
系统win10 pro 64位，shadowsock2.5.2。最近刚升级到win10，多次出现无法翻墙使用的情况，国内网页可以正常打开。但是有时候又突然可以翻墙。logs如下：
[2015-08-06 13:23:05] Shadowsocks started
[2015-08-06 13:23:37] failed to recv data in handshakeReceive2Callback
[2015-08-06 13:23:42] failed to recv data in handshakeReceive2Callback
[2015-08-06 13:23:43] failed to recv data in handshakeReceive2Callback
[2015-08-06 13:24:03] failed to recv data in handshakeReceive2Callback

[2015-08-06 11:55:15] System.Net.Sockets.SocketException (0x80004005): An invalid argument was supplied
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at Shadowsocks.Controller.Handler.StartConnect()

[2015-08-06 21:51:24] Shadowsocks started
[2015-08-06 21:55:40] System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)
求帮助！先谢谢啦！

**Comment by clowwindy** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/247

**Comment by geyunfei** [comment]
我的win10也这样，把迅雷卸了就好了

**Comment by earthday** [comment]
卸载迅雷，ok了。

**Comment by yuanbian150** [comment]
[2015-12-14 14:22:27] System.Net.Sockets.SocketException (0x80004005): 这是在主机名解析时通常出现的暂时错误，它意味着本地服务器没有从权威服务器上收到响应。
   在 System.Net.Dns.GetAddrInfo(String name)
   在 System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   在 System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   在 Shadowsocks.Controller.Handler.

升级WIn10后就这样，请教是什么情况？

**Comment by chenshaoju** [comment]
检查你的域名输入是否正确。

**Comment by Xronger** [comment]
我了个去，果然卸载了迅雷就可以了...

**Comment by yeszao** [comment]
得到一个不用卸载迅雷的解决方法：
禁用xlserviceplatform服务。
打开C:\Program Files\Common Files\Thunder Network\ServicePlatform\XLSP.dll将里面的内容清空之后保存(64位系统为C:\Program Files (x86)\Common Files\Thunder Network\ServicePlatform\XLSP.dll)。
问题解决。
解决方法来源：[](http://xiaix.me/blog/27.html)

**Comment by yeszao** [comment]
我的方法是，关闭服务器端防火墙，就可以了

**Comment by jello-chen** [comment]
禁用xlserviceplatform服务之后，好像真好了

**Comment by jello-chen** [comment]
禁用xlserviceplatform服务之后，好像真好了

**Comment by jello-chen** [comment]
禁用xlserviceplatform服务之后，好像真好了
