### ISSUE TITLE
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### ISSUE THREAD

**Issue by sqd** [shadowsocks/shadowsocks-windows#271]
时不时会在log里面看到一连排的这个错误，导致加载网页的延时大大增加。
应该不是服务器的锅（使用别的shadowsocks客户端加载延时均正常）

[2015-08-13 20:00:08] System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)

**Comment by clowwindy** [comment]
1. OS, 版本
2. 别的客户端是指什么客户端
3. 是否测试过老版本
4. 是否排查过 https://github.com/shadowsocks/shadowsocks/wiki/Troubleshooting

**Comment by sqd** [comment]
未能复现...难道是网络定时性抽风？
我错了Orz
