### ISSUE TITLE
自建机场搭的小飞机，服务器没被墙，但是就是不能翻墙

### ISSUE THREAD

**Issue by okcrose** [shadowsocks/shadowsocks-windows#2713]
公司的网不能翻墙，但是家里的网和手机都可以。请大佬指教！！
日志如下：
[2019-12-03 13:46:23] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-12-03 13:46:23] Shadowsocks started (4.1.8.0)
[2019-12-03 13:46:24] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-12-03 13:46:24] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-12-03 13:46:26] connect to api.github.com:443
[2019-12-03 13:46:27] connect to www.gstatic.com:443
[2019-12-03 13:46:27] connect to www.gstatic.com:443
[2019-12-03 13:46:27] connect to accounts.google.com:443
[2019-12-03 13:46:27] connect to www.googleapis.com:443
[2019-12-03 13:46:27] Socket connected to ss server: hk (???)
[2019-12-03 13:46:27] Socket connected to ss server: hk (???)
[2019-12-03 13:46:27] connect to www.googleapis.com:443
[2019-12-03 13:46:27] connect to www.googleapis.com:443
[2019-12-03 13:46:28] connect to www.google.com:443
[2019-12-03 13:46:28] Socket connected to ss server: hk (???)
[2019-12-03 13:46:28] connect to clients1.google.com:443
[2019-12-03 13:46:28] Socket connected to ss server: hk (???)
[2019-12-03 13:46:29] connect to www.googleapis.com:443
[2019-12-03 13:46:29] Socket connected to ss server: hk (???)
[2019-12-03 13:46:31] hk (???) timed out
[2019-12-03 13:46:31] connect to api.github.com:443
[2019-12-03 13:46:31] Socket connected to ss server: hk (???)
[2019-12-03 13:46:32] hk (34.92.78.249:1234) timed out
[2019-12-03 13:46:32] hk (34.92.78.249:1234) timed out
[2019-12-03 13:46:32] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-12-03 13:46:32] hk (???) timed out
[2019-12-03 13:46:32] hk (???) timed out
[2019-12-03 13:46:38] connect to clients2.google.com:443
[2019-12-03 13:46:38] connect to www.google.com:443
[2019-12-03 13:46:38] connect to mtalk.google.com:5228
[2019-12-03 13:46:39] Socket connected to ss server: hk (???)
[2019-12-03 13:46:39] Socket connected to ss server: hk (???)
[2019-12-03 13:46:46] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-12-03 13:46:51] connect to accounts.google.com:443
[2019-12-03 13:46:51] Socket connected to ss server: hk (???)
[2019-12-03 13:46:52] connect to www.googleapis.com:443
[2019-12-03 13:46:52] Socket connected to ss server: hk (???)
[2019-12-03 13:46:54] connect to www.google.com:443
[2019-12-03 13:46:56] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
日志……呢？

**Comment by okcrose** [comment]
> 
> 
> 日志…

**Comment by okcrose** [comment]
> 
> 
> 日志……呢？

贴上去了

**Comment by chenshaoju** [comment]
`Authentication failed because the remote party has closed the transport stream.` 确保你的IP地址、端口、加密方式、密码正确。

如果确认无误，有可能是你的公网IP被关照了，可以尝试套个插件看看（包括服务端）：
https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by wuweijian1997** [comment]
别的地方看到的，电信的好像翻不了，移动联通的可以。不知道真假，反正我联通手机f一点问题也没有，家里WiFi一点都翻不了，公司的WiFi可以翻。

**Comment by okcrose** [comment]
> 别的地方看到的，电信的好像翻不了，移动联通的可以。不知道真假，反正我联通手机f一点问题也没有，家里WiFi一点都翻不了，公司的WiFi可以翻。

我是公司的不能翻，家里的随便翻。现在套了OBFS，公司也可以了。

**Comment by wuweijian1997** [comment]
> > 别的地方看到的，电信的好像翻不了，移动联通的可以。不知道真假，反正我联通手机f一点问题也没有，家里WiFi一点都翻不了，公司的WiFi可以翻。
> 
> 我是公司的不能翻，家里的随便翻。现在套了OBFS，公司也可以了。

有没有教程？速度怎么样？我的手机流量访问速度很快，用WiFi感觉就不太行
