### ISSUE TITLE
能否增加类似定时重启的功能

### ISSUE THREAD

**Issue by stanleyxu2005** [shadowsocks/shadowsocks-windows#274]
我发现多次timeout之后，这个代理服务就无法接受新的请求了。我只好把客户端重启一下。能否看看这个什么bug，或者索性增加一个定时重启，如果我每小时可以自动一次客户端，也就觉察不出断链的存在。

我在log里面看见的信息如下
```
[2015-08-16 09:26:22] System.Net.Sockets.SocketException (0x80004005): An invalid argument was supplied
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at Shadowsocks.Controller.Handler.StartConnect()
```

**Comment by clowwindy** [comment]
有其他人遇到这个问题么？

**Comment by stanleyxu2005** [comment]
用了最新的2.5.4
```
[2015-08-17 16:32:14] System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)
```
差不多每个小时1-2次。

**Comment by stanleyxu2005** [comment]
不过比2.5.2好，至少我今天还没有重启过ss

**Comment by clowwindy** [comment]
如果没有其他人遇到，就自己写个 bat 文件吧：

```
:loop
start a.exe
timeout 5
taskkill /f /im a.exe
goto loop
```

**Comment by stanleyxu2005** [comment]
ok
