### ISSUE TITLE
从3.4.2.1升级到4.1.9.2后AWS架设的代理失效 怀疑路由器被更改

### ISSUE THREAD

**Issue by Akitsuki1551** [shadowsocks/shadowsocks-windows#2838]
早上代理运作一切正常 从3.4.2.1升级到4.1.9.2后 AWS架设的代理失效 人在美国

测试手段如下
尝试让朋友使用我的代理一切正常
拔除路由后直连调制解调器 一切正常
手机通过路由连接代理无法工作
手机通过移动数据连接代理一切正常
重设路由后尝试连接代理 无法工作
QQ以及其他的即时通信软件可以正常通过路由运作
Telnet尝试连接端口 直连以及通过路由都能测试成功
把全部设置文件删除后初始化SS客户端 无法工作
删除4.1.9.2后运行3.4.2.1也是无法正常通过路由运作
在平板上运行之前备份下来的SS也是出现同样的问题
平板通过手机热点连接的话能正常运作

日志如下

[2020-03-29 22:37:35] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2020-03-29 22:43:45] Shadowsocks started
[2020-03-29 22:43:47] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

请问有什么解决方法

**Comment by chenshaoju** [comment]
```
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
```

这个的意思是，从你的计算机到你的服务器连接被重置了。

简而言之，被墙了，和你升级没有关系。

请尝试换个端口，或者套个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2824

**Comment by Akitsuki1551** [comment]
> 
> 
> ```
> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
> ```
> 
> 这个的意思是，从你的计算机到你的服务器连接被重置了。
> 
> 简而言之，被墙了，和你升级没有关系。
> 
> 请尝试换个端口，或者套个插件：#2824

谢谢 但是我想知道为什么不通过路由直接连接代理的话 代理能正常工作
我试了家中2台电脑 一台手机 一台平板 都是出现接上路由就不能连通 然后直连调制调解器就能正常使用代理

**Comment by chenshaoju** [comment]
我也没见过这个现象，感觉是你的路由器里是不是设置了什么屏蔽或者过滤？

比如，某些路由器可能存在DDoS保护，若同时发起的TCP连接过多，就直接切断之类的？

**Comment by celeron533** [comment]
路由器是否添加过静态路由条目？ACL屏蔽域名或IP？路由黑洞？

**Comment by eromoe** [comment]
我今天3.3. 升级到 4.1.10 就无法使用了，关掉4.1.10 再开 3.3 也不行了。。
