### ISSUE TITLE
Shadowsocks.Util.SystemProxy.ProxyException: Error query options: 5

### ISSUE THREAD

**Issue by arthurcrh** [shadowsocks/shadowsocks-windows#2929]
-->

### Describe the bug

[2020-08-07 11:55:09] Shadowsocks started
[2020-08-07 11:55:09] Shadowsocks.Util.SystemProxy.ProxyException: Error query options: 5 拒绝访问。

SS worked in my PC 1 year ago, now I moved it into a new place, and SS stopped working like that.

### Environment
Win7 x64

- .NET version: 4.72      c++ 2017

### Config and error log in detail (with all sensitive info masked)

```
 at Shadowsocks.Util.SystemProxy.Sysproxy.ExecSysproxy(String arguments)
   at Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
[2020-08-07 11:55:09] Shadowsocks started
[2020-08-07 11:55:09] Shadowsocks.Util.SystemProxy.ProxyException: Error query options: 5 拒绝访问。



   at Shadowsocks.Util.SystemProxy.Sysproxy.ExecSysproxy(String arguments)
   at Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
[2020-08-07 11:55:17] ***************** timed out
[2020-08-07 11:55:17] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
Please check this service is running:
![image](https://user-images.githubusercontent.com/515763/60673007-57ba4e80-9ea9-11e9-91c1-ef1a5a96581f.png)

**Comment by studentmain** [comment]
> now I moved it into a new place

看看是不是目录权限不够

**Comment by arthurcrh** [comment]
> Please check this service is running:
> ![image](https://user-images.githubusercontent.com/515763/60673007-57ba4e80-9ea9-11e9-91c1-ef1a5a96581f.png)

Checked, that service is in activatiion already.

**Comment by chenshaoju** [comment]
This issue may cause by your security software, Some security software may have a function like `System protect` or `Browser protect` etc...

Please disable your security software and try again.

https://github.com/shadowsocks/shadowsocks-windows/issues/2100
