### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by Jeff-Tew** [shadowsocks/shadowsocks-windows#2968]
Shadowsocks version 4.1.10.0 on Ubuntu 18.04.5. Got the following errors when trying to connect from my laptop (Windows 10) to ss-server:

2020-09-21 22:12:51.4801|INFO|Shadowsocks.Controller.TCPHandler|167.71.228.22:9549 timed out
2020-09-21 22:12:51.6249|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

I've checked the IP reachability, port is open and netstat showed that the port is in the state of "listening". Firewall (iptable and ufw) has been set correctly, ufw disabled and port 9549 (the one I chose) is set as open on iptable.

Status of the port:
root@ubuntu:~# sudo netstat -ntlp | grep LISTEN
tcp 0 0 0.0.0.0:9549 0.0.0.0:* LISTEN 31160/ss-server

UFW:
root@ubuntu:~# ufw status
Status: inactive

iptable：
root@ubuntu:~# sudo iptables -L INPUT
Chain INPUT (policy ACCEPT)
target prot opt source destination
ACCEPT tcp -- anywhere anywhere tcp dpt:8388 /* Shadowsocks server listen port /
ACCEPT tcp -- anywhere anywhere tcp dpt:9549 / Shadowsocks server listen port */

Also "nmap"ed the IP+port combo, it looked nothing but normal. 

I'm at the end of my wits here, anyone who has an idea why?

**Comment by chenshaoju** [comment]
重复，移动到：https://github.com/shadowsocks/shadowsocks-windows/issues/2967。
