### ISSUE TITLE
Corporate AV software blocks sysproxy.exe and SS fails to start even though system proxy is turned off

### ISSUE THREAD

**Issue by lcferrum** [shadowsocks/shadowsocks-windows#2972]
My corporate AV blocks sysproxy.exe (System Proxy Agent) and I don't have permissions to whitelist it.
But my SS instance has "System proxy" option turned off and shouldn't use it. Nevertheless, it now exits with following error:

```
System.InvalidOperationException: No process is associated with this object.

   at System.Diagnostics.Process.EnsureState(State state)

   at System.Diagnostics.Process.EnsureState(State state)

   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)

   at System.Diagnostics.Process.WaitForExit(Int32 milliseconds)

   at System.Diagnostics.Process.WaitForExit()

   at Shadowsocks.Util.SystemProxy.Sysproxy.ExecSysproxy(String arguments)

   at Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)

   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv, Boolean noRetry)

   at Shadowsocks.Controller.ShadowsocksController.Reload()

   at Shadowsocks.Controller.ShadowsocksController.Start(Boolean regHotkeys)

   at Shadowsocks.Program.Main(String[] args)
```

Suggestion: do not run sysproxy.exe if corresponding option is turned off.

**Comment by chenshaoju** [comment]
Can you tell us what your AV Software name? Some may have a webpage can send sample as false positives.

**Comment by lcferrum** [comment]
It's BeyondTrust and I'm afraid this is more about access management - the thing blocks some software types based on my organization policy. So I can't just mark it as false positive.

Anyway, In my opinion SS shouldn't try to launch System Proxy Agent if it's not needed by current configuration.

**Comment by database64128** [comment]
Please try out the latest build artifacts from our [v5/master](https://github.com/shadowsocks/shadowsocks-windows/tree/v5/master) branch: https://ci.appveyor.com/project/celeron533/shadowsocks-windows/build/job/r8oncfu98gee5u8e/artifacts

If you already have .NET Core 3.1 installed, download the minimal zip. If not, you may choose to install the runtime and use the minimal zip, or download the portable zip with embedded runtime.

**Comment by lcferrum** [comment]
Yes, v5/master works and doesn't try to launch System Proxy Agent, thanks!

**Comment by lcferrum** [comment]
V5 branch is gone and current release still tries to launch sysproxy.exe (System Proxy Agent) when it's no needed.
