### ISSUE TITLE
Error when update PAC from Geosite

### ISSUE THREAD

**Issue by samirmh-dev** [shadowsocks/shadowsocks-windows#2986]
## Error: The given key was not present in the dictionary

![image](https://user-images.githubusercontent.com/54883542/95777036-76c3a500-0cd6-11eb-8488-c50cf1337b00.png)

OS: **Windows 10 19041.508**
Client version: **4.2.1.0**
.Net version >= 4.7
VS2015 installed

Error shows that AZ locale is not configured. But the questions is why Client not using fallback locale (EN) ?

```
2020-10-12 21:54:15.2351|INFO|Shadowsocks.Controller.I18N|Current language is: az-Latn-AZ
2020-10-12 21:54:15.2586|INFO|Shadowsocks.Controller.I18N|Translation for az-Latn-AZ not found
2020-10-12 21:54:15.6200|ERROR|Shadowsocks.Program|System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Shadowsocks.Controller.GeositeUpdater.MergeAndWritePACFile(String group, Boolean blacklist)
   at Shadowsocks.Controller.PACDaemon.TouchPACFile()
   at Shadowsocks.Controller.PACDaemon..ctor(Configuration config)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   at Shadowsocks.Controller.ShadowsocksController.Start(Boolean regHotkeys)
   at Shadowsocks.Program.Main(String[] args)
2020-10-12 21:59:02.8149|INFO|Shadowsocks.Controller.I18N|Current language is: az-Latn-AZ
2020-10-12 21:59:02.8399|INFO|Shadowsocks.Controller.I18N|Translation for az-Latn-AZ not found
2020-10-12 21:59:03.1659|ERROR|Shadowsocks.Program|System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Shadowsocks.Controller.GeositeUpdater.MergeAndWritePACFile(String group, Boolean blacklist)
   at Shadowsocks.Controller.PACDaemon.TouchPACFile()
   at Shadowsocks.Controller.PACDaemon..ctor(Configuration config)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   at Shadowsocks.Controller.ShadowsocksController.Start(Boolean regHotkeys)
   at Shadowsocks.Program.Main(String[] args)
2020-10-12 22:03:07.9780|INFO|Shadowsocks.Controller.I18N|Current language is: az-Latn-AZ
2020-10-12 22:03:07.9940|INFO|Shadowsocks.Controller.I18N|Translation for az-Latn-AZ not found

```

**Comment by studentmain** [comment]
try v4.2.0.1

**Comment by studentmain** [comment]
Can you post gui-config.json here with sensitive information masked?

**Comment by database64128** [comment]
First of all, you have not provided enough information to help diagnose the issue.

Second, I have just finished dozens of tests. The only case where your issue can happen, is when you delete `pac.txt` and manually change `geositeGroup` to some invalid group in `gui-config.json`.

Improvements are coming very soon to prevent the crash and show a message box telling the user they have misconfigured the geosite group. But I wouldn't call it a bug, as it can only happen when the user changes the configuration file without knowing what they have done can lead to undefined behaviors. For now, I'm closing the issue.

**Comment by samirmh-dev** [comment]
> try v4.2.0.1

the same result happens

**Comment by samirmh-dev** [comment]
> First of all, you have not provided enough information to help diagnose the issue.
> 
> Second, I have just finished dozens of tests. The only case where your issue can happen, is when you delete `pac.txt` and manually change `geositeGroup` to some invalid group in `gui-config.json`.
> 
> Improvements are coming very soon to prevent the crash and show a message box telling the user they have misconfigured the geosite group. But I wouldn't call it a bug, as it can only happen when the user changes the configuration file without knowing what they have done can lead to undefined behaviors. For now, I'm closing the issue.

@database64128 I didn't edit any source file. You can test bug with this steps:

1. Use Windows 10 >= v19041.508
2. Change language to **Azerbaijan (Latin)** on **Region Format > Current format**

![image](https://user-images.githubusercontent.com/54883542/95821644-5417a780-0d3b-11eb-859f-4a5b1b91c77d.png)

3. Open Application and that error will happen.


Currently I handled it with changing default locale to **English (US)** and everything is OK now.

**Comment by database64128** [comment]
Thanks for the steps! A quick fix is coming.

**Comment by database64128** [comment]
Please try the latest build artifacts at https://ci.appveyor.com/project/celeron533/shadowsocks-windows/build/job/28i7h5xsmq9gy7pt/artifacts

**Comment by samirmh-dev** [comment]
@database64128 

Just tested and v4.2.0.54 is working as expected 👍🏽
