### ISSUE TITLE
win7启动异常

### ISSUE THREAD

**Issue by wangyp910888** [shadowsocks/shadowsocks-windows#2992]
下载shodowsock5客户端登录服务端，启动时报以下错误:
2020-10-18 10:54:01.6077|WARN|Shadowsocks.Model.Configuration|System.ArgumentException: Font 'Consolas' does not support style 'Regular'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize)
   at Shadowsocks.Model.LogViewerConfig..ctor()
   at CreateShadowsocks.Model.LogViewerConfig()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Shadowsocks.Model.Configuration.Load()
2020-10-18 10:54:01.6677|ERROR|Shadowsocks.Program|System.TypeInitializationException: The type initializer for 'Shadowsocks.Controller.AvailabilityStatistics' threw an exception. ---> System.ArgumentException: Font 'Consolas' does not support style 'Regular'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize)
   at Shadowsocks.Model.LogViewerConfig..ctor()
   at Shadowsocks.Model.Configuration.Load()
   at Shadowsocks.Util.Utils.GetTempPath()
   at Shadowsocks.Util.Utils.GetTempPath(String filename)
   at Shadowsocks.Controller.AvailabilityStatistics..cctor()
   --- End of inner exception stack trace ---
   at Shadowsocks.Controller.AvailabilityStatistics.get_Instance()
   at Shadowsocks.Controller.ShadowsocksController..ctor()
   at Shadowsocks.Program.Main(String[] args)
2020-10-18 10:54:01.6867|INFO|Shadowsocks.Controller.I18N|Current language is: zh-CN

Shadowsocks客户端版本：   4.2.0.1
- 操作系统版本：   windows7 旗舰版
- .NET版本：   .net 4.7   

配置文件
{
  "version": "4.2.0.1",
  "configs": [
    {
      "server": "",
      "server_port": 1388,
      "password": "",
      "method": "chacha20",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 0,
  "global": true,
  "enabled": true,
  "shareOverLan": true,
  "isDefault": false,
  "localPort": 11080,
  "portableMode": true,
  "showPluginOutput": false,
  "pacUrl": "",
  "useOnlinePac": true,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "isIPv6Enabled": false,
  "generateLegacyUrl": false,
  "geositeUrl": null,
  "geositeGroup": "geolocation-!cn",
  "geositeBlacklistMode": true,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3,
    "useAuth": false,
    "authUser": "",
    "authPwd": ""
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  }
}

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1940
