### ISSUE TITLE
使用最新版本的KCPTUN插件无法上网，换上老的插件就可以了，是什么情况？

### ISSUE THREAD

**Issue by c21xdx** [shadowsocks/shadowsocks-windows#3027]
### 环境

- Shadowsocks客户端版本：Shadowsocks-4.3.2.146
- 操作系统版本：WIN7
- .NET版本：.NET Framework 4.7.2

### 操作步骤
下载了最新版本的SS客户端和client_windows_amd64插件。无法上网。用旧版本的client_windows_amd64替换掉后，就可以了。
就是kcptun-windows-amd64-20201010.tar.gz这个版本的插件上不了网，使用旧版本插件可以。

### 期望的结果
使用新版本KCP插件时候可以正常上网

### 配置文件和日志文件（请隐去敏感信息）

```
2020-11-15 11:01:55.7813|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
```

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/3013

**Comment by database64128** [comment]
Please report the issue to the plugin's repository.
