### ISSUE TITLE
Not working Windows 10 

### ISSUE THREAD

**Issue by macmiller** [shadowsocks/shadowsocks-windows#3126]
### Describe the bug
I am upgrading from 4.3.3.170.  I am running 4.3.3.170 in portable mode and it works fine.  I am using foxy proxy in Chrome to connect.  All working --> upgrade to 4.4.0.185 and it can't connect.  Double checked all settings and they are the same.  I can go back and forth between 4.3.3.170 and 4.4.0.185 and it is the same, 4.3.3.170 always works no problem, 4.4.0.185 can't connect.  
### Environment

- Shadowsocks client version:
- OS version: Windows 10
- .NET version:

### Steps you have tried
Looking at all of the setting and making sure the setting match.  Rebooting each time and then trying 4.4.0.185 and then rebooting again and using 4.3.3.170 which always works.

### What did you expect to see?
I would expect 4.4.0.185 to work the same as 4.3.3.170

### What did you see instead?
Can't connect.

### Config and error log in detail (with all sensitive info masked)

```
PASTE LOG HERE
There was one port in use error, since corrected by stopping other shadowsocks and rebooting and starting this one.

```2021-03-07 13:15:08.6707|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2021-03-07 13:15:08.6947|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2021-03-07 13:15:08.9940|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:15:09.4396|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:15:19.7789|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:15:19.9391|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:17:26.1842|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:17:26.3482|WARN|Shadowsocks.Controller.ShadowsocksController|System.Exception: Port 3054 already in use
   at Shadowsocks.Controller.Listener.Start(Configuration config)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
2021-03-07 13:17:43.3182|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:17:43.4506|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:17:53.1929|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:17:53.3497|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:18:07.9107|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:18:08.0394|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:19:55.7657|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:19:55.9067|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:31:34.6831|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2021-03-07 13:31:34.7144|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2021-03-07 13:31:36.8392|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2021-03-07 13:31:36.8612|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2021-03-07 13:31:36.9743|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:31:37.3365|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:31:47.5938|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:31:47.7615|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:32:35.2573|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:32:35.4132|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:37:22.3088|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2021-03-07 13:37:22.3598|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2021-03-07 13:37:22.5147|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:37:23.0403|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:37:33.2968|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:37:33.4348|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:37:39.3711|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:37:39.5032|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:39:37.2330|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:39:37.3814|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:40:54.8454|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2021-03-07 13:40:54.8684|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2021-03-07 13:40:54.9657|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:40:55.1662|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:41:05.3843|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:41:05.5536|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:41:50.2984|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2021-03-07 13:41:50.3297|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2021-03-07 13:41:50.4456|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:41:50.6485|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-03-07 13:42:00.8982|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2021-03-07 13:42:01.0206|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)```

**Comment by database64128** [comment]
> Port 3054 already in use

The log already told you the problem.

**Comment by macmiller** [comment]
I had put this at the top of the log output.  In any event the port being open was an old error message.  However I did find the problem.  

top of log output:
There was one port in use error, since corrected by stopping other shadowsocks and rebooting and starting this one.
