### ISSUE TITLE
SIP002 Online configuration update doesn't work with TLS1.3.

### ISSUE THREAD

**Issue by fernvenue** [shadowsocks/shadowsocks-windows#3316]
### Describe the bug
When [SIP002](https://github.com/shadowsocks/shadowsocks-org/wiki/SIP002-URI-Scheme) configuration server only allows TLS1.3, [shadowsocks-windows](https://github.com/shadowsocks/shadowsocks-windows) fails to establish connection.

### Environment

- Shadowsocks client version: [4.4.1.0](https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.4.1.0)
- OS version: Windows 10 LTSC 2021 with 21H2
- .NET version: v4.0

### Steps you have tried
After I discovered this issue, I updated the SSL/TLS configuration from my service provider Cloudflare to allow TLS1.2 connections, and then shadowsocks-windows successfully connected to the server.

### What did you expect to see?
I think this feature should work with TLS1.3.

### What did you see instead?
SIP002 Online configuration update doesn't work with TLS1.3.

### Config and error log in detail (with all sensitive info masked)

```
2022-05-2x xx:xx:xx.xxxx|WARN|Shadowsocks.Controller.ShadowsocksController|System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Shadowsocks.Controller.Service.OnlineConfigResolver.<GetOnline>d__0.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Shadowsocks.Controller.ShadowsocksController.<UpdateOnlineConfigInternal>d__109.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Shadowsocks.Controller.ShadowsocksController.<UpdateAllOnlineConfig>d__111.MoveNext()
...
```

**Comment by HeyBroWhatsUp** [comment]
.net framework 4.8 doesn't support tls1.3.
