### ISSUE TITLE
运行提示找不到指定文件

### ISSUE THREAD

**Issue by Lion-Yan** [shadowsocks/shadowsocks-windows#3327]
### 环境

- Shadowsocks客户端版本：4.4.1.0
- 操作系统版本：Windows7
- .NET版本：4.7.1

### 操作步骤
打开exe

### 期望的结果
正常运行

### 实际结果
弹框报错

### 配置文件和日志文件（请隐去敏感信息）

```
![image](https://user-images.githubusercontent.com/57982859/175505461-5df83820-8a27-4b84-b5ae-ac34e004ce99.png)
2022-06-24 16:58:43.5850|ERROR|Shadowsocks.Program|System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 系统找不到指定的文件。
File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Shadowsocks.Controller.ShadowsocksController..ctor()
   at Shadowsocks.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2022-06-24 16:58:43.6215|INFO|Shadowsocks.Controller.I18N|Current language is: zh-CN
2022-06-24 17:02:19.6705|ERROR|Shadowsocks.Program|System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 系统找不到指定的文件。
File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Shadowsocks.Controller.ShadowsocksController..ctor()
   at Shadowsocks.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2022-06-24 17:02:19.7150|INFO|Shadowsocks.Controller.I18N|Current language is: zh-CN

```

**Comment by chenshaoju** [comment]
请安装 4.8 版本的 .net framework，如果提示已经安装，请点击修复安装看看：https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-offline-installer
