### ISSUE TITLE
错误:找不到插件程序文件

### ISSUE THREAD

**Issue by LS3213** [shadowsocks/shadowsocks-windows#3371]
### 简要描述问题
在添加服务器时显示错误:找不到插件程序文件
![mmexport1672336515196](https://user-images.githubusercontent.com/82749659/209992262-1e2fae1a-739f-4862-bc2e-0c54453788c2.png)

### 环境

- Shadowsocks客户端版本：windows 7
- 操作系统版本：4.4.1.0
- .NET版本：4.8

### 操作步骤
扫码添加服务器

### 期望的结果
正常代理成功

### 实际结果
错误:找不到插件程序文件

### 配置文件和日志文件（请隐去敏感信息）

```
2022-12-30 01:49:58.8459|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: zh-CN
2022-12-30 01:49:58.8919|DEBUG|Shadowsocks.Controller.PACServer|Set PAC URL:http://127.0.0.1:1080/pac?hash=aP9esBdy1Q_7XzF69LAkKQ2&secret=NxKn9T_-u8hvV-Z29VcdR2IKER-bhPNX-jQlUQwKes01
2022-12-30 01:49:58.8919|ERROR|Shadowsocks.Controller.ShadowsocksController|Failed to start SIP003 plugin: 找不到插件程序文件
2022-12-30 01:49:58.8919|WARN|Shadowsocks.Controller.ShadowsocksController|System.IO.FileNotFoundException: 找不到插件程序文件
File name: 'v2ray' ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   at Shadowsocks.Controller.ShadowsocksController.GetPluginLocalEndPointIfConfigured(Server server)
   at Shadowsocks.Controller.ShadowsocksController.StartPlugin()
   at Shadowsocks.Controller.ShadowsocksController.Reload()
2022-12-30 01:50:01.9531|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
2022-12-30 01:50:13.4787|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
2022-12-30 01:50:15.0378|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: zh-CN
2022-12-30 01:50:15.0378|DEBUG|Shadowsocks.Controller.PACServer|Set PAC URL:http://127.0.0.1:1080/pac?hash=aP9esBdy1Q_7XzF69LAkKQ2&secret=NxKn9T_-u8hvV-Z29VcdR2IKER-bhPNX-jQlUQwKes01
2022-12-30 01:50:15.0378|ERROR|Shadowsocks.Controller.ShadowsocksController|Failed to start SIP003 plugin: 找不到插件程序文件
2022-12-30 01:50:15.0378|WARN|Shadowsocks.Controller.ShadowsocksController|System.IO.FileNotFoundException: 找不到插件程序文件
File name: 'v2ray' ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   at Shadowsocks.Controller.ShadowsocksController.GetPluginLocalEndPointIfConfigured(Server server)
   at Shadowsocks.Controller.ShadowsocksController.StartPlugin()
   at Shadowsocks.Controller.ShadowsocksController.Reload()
2022-12-30 01:50:16.6899|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
2022-12-30 01:50:23.3333|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).

```

**Comment by LS3213** [comment]
> ### 简要描述问题
> 在添加服务器时显示错误:找不到插件程序文件 ![mmexport1672336515196](https://user-images.githubusercontent.com/82749659/209992262-1e2fae1a-739f-4862-bc2e-0c54453788c2.png)
> 
> ### 环境
> * Shadowsocks客户端版本：windows 7
> * 操作系统版本：4.4.1.0
> * .NET版本：4.8
> 
> ### 操作步骤
> 扫码添加服务器
> 
> ### 期望的结果
> 正常代理成功
> 
> ### 实际结果
> 错误:找不到插件程序文件
> 
> ### 配置文件和日志文件（请隐去敏感信息）

```

2022-12-30 01:49:58.8459|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: zh-CN
2022-12-30 01:49:58.8919|DEBUG|Shadowsocks.Controller.PACServer|Set PAC URL:http://127.0.0.1:1080/pac?hash=aP9esBdy1Q_7XzF69LAkKQ2&secret=NxKn9T_-u8hvV-Z29VcdR2IKER-bhPNX-jQlUQwKes01
2022-12-30 01:49:58.8919|ERROR|Shadowsocks.Controller.ShadowsocksController|Failed to start SIP003 plugin: 找不到插件程序文件
2022-12-30 01:49:58.8919|WARN|Shadowsocks.Controller.ShadowsocksController|System.IO.FileNotFoundException: 找不到插件程序文件
File name: 'v2ray' ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   at Shadowsocks.Controller.ShadowsocksController.GetPluginLocalEndPointIfConfigured(Server server)
   at Shadowsocks.Controller.ShadowsocksController.StartPlugin()
   at Shadowsocks.Controller.ShadowsocksController.Reload()
2022-12-30 01:50:01.9531|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
2022-12-30 01:50:13.4787|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
2022-12-30 01:50:15.0378|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: zh-CN
2022-12-30 01:50:15.0378|DEBUG|Shadowsocks.Controller.PACServer|Set PAC URL:http://127.0.0.1:1080/pac?hash=aP9esBdy1Q_7XzF69LAkKQ2&secret=NxKn9T_-u8hvV-Z29VcdR2IKER-bhPNX-jQlUQwKes01
2022-12-30 01:50:15.0378|ERROR|Shadowsocks.Controller.ShadowsocksController|Failed to start SIP003 plugin: 找不到插件程序文件
2022-12-30 01:50:15.0378|WARN|Shadowsocks.Controller.ShadowsocksController|System.IO.FileNotFoundException: 找不到插件程序文件
File name: 'v2ray' ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   at Shadowsocks.Controller.ShadowsocksController.GetPluginLocalEndPointIfConfigured(Server server)
   at Shadowsocks.Controller.ShadowsocksController.StartPlugin()
   at Shadowsocks.Controller.ShadowsocksController.Reload()
2022-12-30 01:50:16.6899|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
2022-12-30 01:50:23.3333|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
```

**Comment by LS3213** [comment]
> ### 简要描述问题
> 在添加服务器时显示错误:找不到插件程序文件 ![mmexport1672336515196](https://user-images.githubusercontent.com/82749659/209992262-1e2fae1a-739f-4862-bc2e-0c54453788c2.png)
> 
> ### 环境
> * Shadowsocks客户端版本：windows 7
> * 操作系统版本：4.4.1.0
> * .NET版本：4.8
> 
> ### 操作步骤
> 扫码添加服务器
> 
> ### 期望的结果
> 正常代理成功
> 
> ### 实际结果
> 错误:找不到插件程序文件
> 
> ### 配置文件和日志文件（请隐去敏感信息）
```
> 2022-12-30 01:49:58.8459|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: zh-CN 2022-12-30 01:49:58.8919|DEBUG|Shadowsocks.Controller.PACServer|Set PAC URL:http://127.0.0.1:1080/pac?hash=aP9esBdy1Q_7XzF69LAkKQ2&secret=NxKn9T_-u8hvV-Z29VcdR2IKER-bhPNX-jQlUQwKes01 2022-12-30 01:49:58.8919|ERROR|Shadowsocks.Controller.ShadowsocksController|Failed to start SIP003 plugin: 找不到插件程序文件 2022-12-30 01:49:58.8919|WARN|Shadowsocks.Controller.ShadowsocksController|System.IO.FileNotFoundException: 找不到插件程序文件 File name: 'v2ray' ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。 at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) at System.Diagnostics.Process.Start() at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded() at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded() at Shadowsocks.Controller.ShadowsocksController.GetPluginLocalEndPointIfConfigured(Server server) at Shadowsocks.Controller.ShadowsocksController.StartPlugin() at Shadowsocks.Controller.ShadowsocksController.Reload() 2022-12-30 01:50:01.9531|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode). 2022-12-30 01:50:13.4787|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode). 2022-12-30 01:50:15.0378|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: zh-CN 2022-12-30 01:50:15.0378|DEBUG|Shadowsocks.Controller.PACServer|Set PAC URL:http://127.0.0.1:1080/pac?hash=aP9esBdy1Q_7XzF69LAkKQ2&secret=NxKn9T_-u8hvV-Z29VcdR2IKER-bhPNX-jQlUQwKes01 2022-12-30 01:50:15.0378|ERROR|Shadowsocks.Controller.ShadowsocksController|Failed to start SIP003 plugin: 找不到插件程序文件 2022-12-30 01:50:15.0378|WARN|Shadowsocks.Controller.ShadowsocksController|System.IO.FileNotFoundException: 找不到插件程序文件 File name: 'v2ray' ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。 at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) at System.Diagnostics.Process.Start() at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded() at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded() at Shadowsocks.Controller.ShadowsocksController.GetPluginLocalEndPointIfConfigured(Server server) at Shadowsocks.Controller.ShadowsocksController.StartPlugin() at Shadowsocks.Controller.ShadowsocksController.Reload() 2022-12-30 01:50:16.6899|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode). 2022-12-30 01:50:23.3333|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
```

**Comment by LS3213** [comment]
> ### 简要描述问题
> 在添加服务器时显示错误:找不到插件程序文件 ![mmexport1672336515196](https://user-images.githubusercontent.com/82749659/209992262-1e2fae1a-739f-4862-bc2e-0c54453788c2.png)
> 
> ### 环境
> * Shadowsocks客户端版本：windows 7
> * 操作系统版本：4.4.1.0
> * .NET版本：4.8
> 
> ### 操作步骤
> 扫码添加服务器
> 
> ### 期望的结果
> 正常代理成功
> 
> ### 实际结果
> 错误:找不到插件程序文件
> 
> ### 配置文件和日志文件（请隐去敏感信息）

```
2022-12-30 01:49:58.8459|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: zh-CN
2022-12-30 01:49:58.8919|DEBUG|Shadowsocks.Controller.PACServer|Set PAC URL:http://127.0.0.1:1080/pac?hash=aP9esBdy1Q_7XzF69LAkKQ2&secret=NxKn9T_-u8hvV-Z29VcdR2IKER-bhPNX-jQlUQwKes01
2022-12-30 01:49:58.8919|ERROR|Shadowsocks.Controller.ShadowsocksController|Failed to start SIP003 plugin: 找不到插件程序文件
2022-12-30 01:49:58.8919|WARN|Shadowsocks.Controller.ShadowsocksController|System.IO.FileNotFoundException: 找不到插件程序文件
File name: 'v2ray' ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   at Shadowsocks.Controller.ShadowsocksController.GetPluginLocalEndPointIfConfigured(Server server)
   at Shadowsocks.Controller.ShadowsocksController.StartPlugin()
   at Shadowsocks.Controller.ShadowsocksController.Reload()
2022-12-30 01:50:01.9531|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
2022-12-30 01:50:13.4787|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
2022-12-30 01:50:15.0378|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: zh-CN
2022-12-30 01:50:15.0378|DEBUG|Shadowsocks.Controller.PACServer|Set PAC URL:http://127.0.0.1:1080/pac?hash=aP9esBdy1Q_7XzF69LAkKQ2&secret=NxKn9T_-u8hvV-Z29VcdR2IKER-bhPNX-jQlUQwKes01
2022-12-30 01:50:15.0378|ERROR|Shadowsocks.Controller.ShadowsocksController|Failed to start SIP003 plugin: 找不到插件程序文件
2022-12-30 01:50:15.0378|WARN|Shadowsocks.Controller.ShadowsocksController|System.IO.FileNotFoundException: 找不到插件程序文件
File name: 'v2ray' ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   at Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   at Shadowsocks.Controller.ShadowsocksController.GetPluginLocalEndPointIfConfigured(Server server)
   at Shadowsocks.Controller.ShadowsocksController.StartPlugin()
   at Shadowsocks.Controller.ShadowsocksController.Reload()
2022-12-30 01:50:16.6899|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
2022-12-30 01:50:23.3333|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).

```

**Comment by chenshaoju** [comment]
这个错误意味着你的SS客户端所使用的代理文件缺少 v2ray 插件，如果你是自己搭建的代理，请确保 shadowsocks.exe 所在目录下有个 v2ray 插件，如果你是购买的SS服务（或称为机场），请与你的SS服务商联系以获得这个插件。

**Comment by LS3213** [comment]
我如何获取这个 v2ray 插件

**Comment by LS3213** [comment]
这个 v2ray 插件 在哪里下载

**Comment by chenshaoju** [comment]
我不太确定，但是你可以试试：https://github.com/shadowsocks/v2ray-plugin/releases 。

**Comment by miss-fang** [comment]
> 这个错误意味着你的SS客户端所使用的代理文件缺少 v2ray 插件，如果你是自己搭建的代理，请确保 shadowsocks.exe 所在目录下有个 v2ray 插件，如果你是购买的SS服务（或称为机场），请与你的SS服务商联系以获得这个插件。

你好，我最近碰到类似文件，但是文件名为obfs-local，请问该如何解决呢？比如去哪里下载对应的插件之类的

**Comment by chenshaoju** [comment]
你好，这里：https://github.com/shadowsocks/simple-obfs/releases
