### ISSUE TITLE
打开Shadowsocks报错

### ISSUE THREAD

**Issue by hjm2007** [shadowsocks/shadowsocks-windows#3427]
### 环境

- Shadowsocks客户端版本：4.4.1.0
- 操作系统版本：Windows 7 32位
- .NET版本：

### 操作步骤
打开"shadowsocks.exe"不久报错

### 期望的结果
正常打开Shadowsocks

### 实际结果
报错未找到文件

### 配置文件和日志文件（请隐去敏感信息）
2023-08-18 09:03:03.3848|ERROR|Shadowsocks.Program|System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 系统找不到指定的文件。
File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Shadowsocks.Controller.ShadowsocksController..ctor()
   at Shadowsocks.Program.Main(String[] args)

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/3152

**Comment by hjm2007** [comment]
谢谢，已经解决了。
