### ISSUE TITLE
I can't start the program. Error System.NullReferenceException 

### ISSUE THREAD

**Issue by ruslansenatorov** [shadowsocks/shadowsocks-windows#3477]
![image](https://github.com/shadowsocks/shadowsocks-windows/assets/55090151/f26dd0ed-b250-4294-960e-34a1c38aa94e)

```
PASTE LOG HERE

2024-05-19 13:50:09.8368|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-05-19 13:50:09.9850|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 185.65.202.19:443 on 127.0.0.1:1468 - PID: 4952
2024-05-19 13:50:10.0030|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-05-19 13:50:20.6506|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-05-19 13:50:20.7956|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 5.182.87.23:443 on 127.0.0.1:1532 - PID: 10020
2024-05-19 13:50:20.8146|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-05-19 13:50:32.5919|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-05-19 13:50:32.7312|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 94.228.168.50:443 on 127.0.0.1:1648 - PID: 16968
2024-05-19 13:50:32.7462|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-05-19 13:50:56.2080|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-05-19 13:50:56.3675|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 5.182.87.23:443 on 127.0.0.1:1921 - PID: 7200
2024-05-19 13:50:56.3941|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-05-19 13:51:01.4082|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-05-19 13:51:01.5640|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:2102 - PID: 14112
2024-05-19 13:51:01.5820|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-05-19 13:51:03.6065|WARN|Shadowsocks.Controller.PortForwarder+Handler|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
2024-05-19 13:53:51.1447|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-05-19 13:53:51.3000|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:25067 - PID: 4304
2024-05-19 13:53:51.3190|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-05-19 14:48:05.5539|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-05-19 14:48:05.6880|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:2884 - PID: 19952
2024-05-19 14:48:05.7110|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-05-19 14:48:05.8157|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-05-19 14:48:05.9565|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:2887 - PID: 7312
2024-05-19 14:48:05.9725|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-05-19 15:01:06.8023|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-05-19 15:01:06.9505|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:20700 - PID: 20808
2024-05-19 15:01:06.9759|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-05-23 22:59:36.6587|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2024-05-23 22:59:36.7061|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2024-05-23 22:59:37.1449|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-05-23 22:59:37.2547|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49697 - PID: 6804
2024-05-23 22:59:37.3281|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-05-23 22:59:47.5230|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-05-23 22:59:47.6639|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49925 - PID: 9176
2024-05-23 22:59:47.6887|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-05-29 18:55:38.0502|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2024-05-29 18:55:38.0991|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2024-05-29 18:55:38.5366|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-05-29 18:55:38.6776|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49695 - PID: 7536
2024-05-29 18:55:38.7709|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-05-29 18:55:48.9683|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-05-29 18:55:49.0933|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49775 - PID: 9964
2024-05-29 18:55:49.1245|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-06-06 08:07:52.0241|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2024-06-06 08:07:52.0709|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2024-06-06 08:07:52.4947|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-06-06 08:07:52.6201|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49692 - PID: 7684
2024-06-06 08:07:52.7448|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-06-06 08:08:02.9049|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-06-06 08:08:03.0457|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49934 - PID: 8884
2024-06-06 08:08:03.0614|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-06-06 09:53:05.4335|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2024-06-06 09:53:05.4804|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2024-06-06 09:53:05.9023|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-06-06 09:53:06.0272|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49700 - PID: 5948
2024-06-06 09:53:06.1528|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-06-06 09:53:16.3429|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-06-06 09:53:16.4959|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:50089 - PID: 8736
2024-06-06 09:53:16.5153|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-06-08 22:13:45.2017|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2024-06-08 22:13:45.2435|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2024-06-08 22:13:45.6829|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-06-08 22:13:45.8084|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49677 - PID: 7252
2024-06-08 22:13:45.9340|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-06-08 22:13:56.1590|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-06-08 22:13:56.3102|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49852 - PID: 9052
2024-06-08 22:13:56.3317|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-06-09 19:31:25.2465|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2024-06-09 19:31:25.2934|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2024-06-09 19:31:25.7308|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-06-09 19:31:25.8558|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49680 - PID: 1612
2024-06-09 19:31:25.9810|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-06-09 19:31:36.1817|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-06-09 19:31:36.3212|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49767 - PID: 8572
2024-06-09 19:31:36.3408|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-06-10 19:27:43.3895|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2024-06-10 19:27:43.4368|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2024-06-10 19:27:43.8760|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-06-10 19:27:44.0014|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49679 - PID: 7600
2024-06-10 19:27:44.1274|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-06-10 19:27:54.4136|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-06-10 19:27:54.5801|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49761 - PID: 5012
2024-06-10 19:27:54.6307|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-06-10 20:15:55.3898|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2024-06-10 20:15:55.4366|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2024-06-10 20:15:55.8763|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-06-10 20:15:55.9861|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49680 - PID: 7220
2024-06-10 20:15:56.0557|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-06-10 20:16:06.2414|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-06-10 20:16:06.3734|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49800 - PID: 9272
2024-06-10 20:16:06.4017|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-06-10 20:17:49.2307|INFO|Shadowsocks.Controller.I18N|Current language is: en-US
2024-06-10 20:17:49.2932|INFO|Shadowsocks.Controller.I18N|Translation for en-US not found
2024-06-10 20:17:49.7151|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-06-10 20:17:49.8561|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for 103.54.56.7:443 on 127.0.0.1:49678 - PID: 7240
2024-06-10 20:17:49.9191|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
```

**Comment by ruslansenatorov** [comment]
fix 

https://github.com/eebssk1/shadowsocks-windows/releases/tag/4.4.1.1
