### ISSUE TITLE
SS连不上求解

### ISSUE THREAD

**Issue by othpark** [shadowsocks/shadowsocks-windows#408]
[2015-12-21 20:11:56] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.Handler.StartConnect()
[2015-12-21 20:11:59] BLABLA (104.156.230.173:7651) timed out
[2015-12-21 20:11:59] BLABLA (104.156.230.173:7651) timed out

**Comment by othpark** [comment]
System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 127.0.0.1:8123
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2015-12-21 20:33:19] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 127.0.0.1:8123
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)

**Comment by GangZhuo** [comment]
请检查自己的服务器设置， IP, 密码，加密方式等等。

**Comment by othpark** [comment]
这里提示一个错误
[root@vultr ~]# ssserver -c /etc/shadowsocks.json
INFO: loading config from /etc/shadowsocks.json
2015-12-22 00:26:37 INFO     loading libcrypto from libcrypto.so.10
2015-12-22 00:26:37 INFO     starting server at 0.0.0.0:7165
Traceback (most recent call last):
  File "/usr/bin/ssserver", line 9, in <module>
    load_entry_point('shadowsocks==2.8.2', 'console_scripts', 'ssserver')()
  File "/usr/lib/python2.6/site-packages/shadowsocks/server.py", line 68, in main
    tcp_servers.append(tcprelay.TCPRelay(a_config, dns_resolver, False))
  File "/usr/lib/python2.6/site-packages/shadowsocks/tcprelay.py", line 582, in __init__
    server_socket.bind(sa)
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use
[root@vultr ~]#

**Comment by chenshaoju** [comment]
@othpark 7156 端口已经被使用，换一个。也可能你启动了两个 ssserver 。

**Comment by vvv0n** [comment]
和我的情况差不多 已经两天不能用了 一直timeout 但是IP可以ping通。

**Comment by othpark** [comment]
错误应该是端口被占用 可改成哪个都不行= =

**Comment by GangZhuo** [comment]
服务器端错误，提交到 https://github.com/shadowsocks/shadowsocks

**Comment by othpark** [comment]
![11](https://cloud.githubusercontent.com/assets/10665808/11954343/bbc62086-a8e2-11e5-9376-12b0cf34b6a3.PNG)
为什么kill进程又会再次出来两个。。。

**Comment by GangZhuo** [comment]
服务端不了解了，你用的服务端是python版的，提交到那里去。

**Comment by shirleypan** [comment]
Error 10106 这个错误可能和TCP/IP协议或Winsock损坏有关。

请尝试以管理员身份启动命令提示符，然后执行：

netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
一行一回车，三行执行完毕后重新启动计算机后再试。
