### ISSUE TITLE
点任何按键都会报错Failed to update registry

### ISSUE THREAD

**Issue by deepller** [shadowsocks/shadowsocks-windows#416]
点任何按键都会popup报错Failed to update registry
以下是log
2015-12-24 10:58:56] Shadowsocks started
[2015-12-24 10:58:57] System.ArgumentException: No server configured
   at Shadowsocks.Controller.Handler.CreateRemote()
   at Shadowsocks.Controller.Handler.StartConnect()
[2015-12-24 10:58:57] System.ArgumentException: No server configured
   at Shadowsocks.Controller.Handler.CreateRemote()
   at Shadowsocks.Controller.Handler.StartConnect()
[2015-12-24 10:59:34] Shadowsocks started
[2015-12-24 10:59:34] Shadowsocks started
[2015-12-24 10:59:51] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.SystemProxy.IEAutoDetectProxy(Boolean set)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
[2015-12-24 10:59:53] Shadowsocks started
[2015-12-24 10:59:53] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.SystemProxy.IEAutoDetectProxy(Boolean set)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
[2015-12-24 11:09:55] Shadowsocks started

**Comment by GangZhuo** [comment]
没有修改注册表权限，请自行搜索解决
