### ISSUE TITLE
更新到3.0无法正常使用

### ISSUE THREAD

**Issue by Tadelaide** [shadowsocks/shadowsocks-windows#501]
我又下载回到2.58可以正常使用
在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2016-03-14 23:53:21] a (*************) timed out
[2016-03-14 23:53:21] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
提示这样的错误 输入的内容都是一样的但是用不了

**Comment by chenshaoju** [comment]
请先尝试该版本是否可以使用：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/sdta3d1rjb46vfop/artifacts

**Comment by Inori-Testarossa** [comment]
可用

**Comment by binhong87** [comment]
3.0会报这个错误，然后退出

[2016-03-11 13:15:16] System.IO.IOException: 文件“E:\下载\翻墙工具\shadowsocks\temp\ss_privoxy.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PolipoRunner..cctor()

**Comment by chenshaoju** [comment]
检查一下任务管理器，是否有一个叫 ss_privoxy.exe 的进程，如果有，结束，然后再试试。

**Comment by willamtang** [comment]
你好，我试了一下，后面发的可以运行。
release里面的我在win10上运行没问题。不过2003和win7无法运行。

**Comment by Halry** [comment]
从2.5.8更新到3.0,用一阵子自动闪退,用起来非常累
[2016-03-15 16:44:08] System.IO.IOException: The process cannot access the file 'C:\Users\halry\AppData\Local\Temp\ss_privoxy.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   at Shadowsocks.Controller.PolipoRunner..cctor()

**Comment by chenshaoju** [comment]
请尝试二楼提供的版本。

**Comment by reg2014** [comment]
win7 64位更新到3.0后出现崩溃的情况，信息如下：
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	3.0.0.0
  问题签名 03:	56d65064
  问题签名 04:	mscorlib
  问题签名 05:	4.0.0.0
  问题签名 06:	53b50a71
  问题签名 07:	22b
  问题签名 08:	10
  问题签名 09:	System.InvalidOperationException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by chenshaoju** [comment]
请尝试二楼提供的版本。

**Comment by reg2014** [comment]
@chenshaoju 要自己编译吗？

**Comment by chenshaoju** [comment]
@reg2014 不需要。

**Comment by aprikyblue** [comment]
+1, and logs:

> [2016-03-04 20:46:48] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'md5_init' in DLL 'libsscrypto'.
   at Shadowsocks.Encryption.MbedTLS.md5_init(IntPtr ctx)
   at Shadowsocks.Encryption.MbedTLS.MD5(Byte[] input)
   at Shadowsocks.Encryption.IVEncryptor.bytesToKey(Byte[] password, Byte[] key)
   at Shadowsocks.Encryption.IVEncryptor.<>c__DisplayClass26_0.<InitKey>b__0(String nk)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Shadowsocks.Encryption.IVEncryptor.InitKey(String method, String password)
   at Shadowsocks.Encryption.PolarSSLEncryptor..ctor(String method, String password, Boolean onetimeauth, Boolean isudp)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password, Boolean onetimeauth, Boolean isudp)
   at Shadowsocks.Controller.TCPHandler.CreateRemote()
   at Shadowsocks.Controller.TCPHandler.StartConnect()

However, the older version works well

**Comment by chenshaoju** [comment]
@aprikyblue Please try This version:
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/sdta3d1rjb46vfop/artifacts

**Comment by jamesrenyd** [comment]
win2008r2 enterprise也出现这样的问题...
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	3.0.0.0
  问题签名 03:	56d65064
  问题签名 04:	Shadowsocks
  问题签名 05:	3.0.0.0
  问题签名 06:	56d65064
  问题签名 07:	1a7
  问题签名 08:	0
  问题签名 09:	System.IO.FileLoadException
  OS 版本:	6.1.7601.2.1.0.274.10
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by chenshaoju** [comment]
＠jamesrenyd 请尝试该版本：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.133/job/h189bju1e18bukk7/artifacts

**Comment by mapleshadow** [comment]
@chenshaoju 你给的这个版本一切正常，我使用没问题！win10 x64

**Comment by aprikyblue** [comment]
@chenshaoju thx

After I delete *libsscrypto.dll* manually, the version can work well

**Comment by cheney256** [comment]
安装.net 4.5可以解决很多出现的问题

**Comment by icuy** [comment]
我用的Windows 10 x64系统，新下载3.0版一运行就自动退出，后来把原先的老配置文件删除掉了，重新设置就能用了。

**Comment by myfingerhurt** [comment]
不知各位注意到没有，v3.0启动时会解压出ss_polipo.exe 和ss_privoxy.exe文件并加入防火墙，这个行为没有在更新中提到，v2.5没有这个行为。请追加说明。

Polipo可以实现缓存加速网页浏览。
Privoxy将Socket5转换成HTTP代理，因为IE和Chrome不支持SOCKS5的远端DNS解析

**Comment by GangZhuo** [comment]
@myfingerhurt ss只会解压出 ss_privoxy.exe ，而且不会自动添加防火墙规则，是否手动允许了？

**Comment by myfingerhurt** [comment]
所以我觉得奇怪，源码里没有ss_polipo.exe的关键字，但
C:\Users\<youname>\AppData\Local\Temp\下出来了ss_polipo.exe和ss_privoxy.exe

我知道了是V2.5.1解压出的ss_polipo.exe. 谢谢楼上.

**Comment by bigtan** [comment]
polipo是老版本的，跟privoxy一个功能。

**Comment by mapleshadow** [comment]
我去，你们讨论偏题了。
官方什么时候更新3。0的这个运行FC的BUG呢？
