### ISSUE TITLE
window10 BUG

### ISSUE THREAD

**Issue by xlplbo** [shadowsocks/shadowsocks-windows#597]
出错信息
System.Net.Sockets.SocketException (0x80004005): The system detected an invalid pointer address in attempting to use a pointer argument in a call
   at System.Net.Sockets.Socket.get_RemoteEndPoint()
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

ipconfig/all :

Ethernet adapter Local Area Connection:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Intel(R) 82579LM Gigabit Network Connection
   Physical Address. . . . . . . . . : 3C-97-0E-E1-06-47
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 192.168.31.117(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : 2016年6月18日 21:53:26
   Lease Expires . . . . . . . . . . : 2016年6月19日 9:53:26
   Default Gateway . . . . . . . . . : 192.168.31.1
   DHCP Server . . . . . . . . . . . : 192.168.31.1
   DNS Servers . . . . . . . . . . . : 192.168.31.1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv6 Address. . . . . . . . . . . : 2001:0:5ef5:79fd:3ca0:8bf:8bec:95a9(Preferred)
   Link-local IPv6 Address . . . . . : fe80::3ca0:8bf:8bec:95a9%2(Preferred)
   Default Gateway . . . . . . . . . : ::
   DHCPv6 IAID . . . . . . . . . . . : 486539264
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1E-06-DB-41-3C-97-0E-E1-06-47
   NetBIOS over Tcpip. . . . . . . . : Disabled

Tunnel adapter isatap.{5A2F1FB1-B41E-4BFE-8EC4-1C4C3377BF25}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #2
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

**Comment by xlplbo** [comment]
找到原因了，原来是端口被占用，把所有程序关一边后就正常了。
