### ISSUE TITLE
 System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by awwang10** [shadowsocks/shadowsocks-windows#601]
今天突然无法用的，上个礼拜上youtube还10Mbps+。
已经试过#476多次，但是没效果。试过两个服务器，都不行。重买了个新的VPS，用新的IP，也不行...
用的是Windows 10。Shadowsocks-windows v2.5.8。

[2016-06-25 03:47:11] System.Net.Sockets.SocketException (0x80004005): An invalid argument was supplied
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at Shadowsocks.Controller.Handler.StartConnect()
[2016-06-25 03:47:12] hk -1 (xxx.xxx.xxx.xxx:8080) timed out
[2016-06-25 03:47:12] hk -1 (xxx.xxx.xxx.xxx:8080) timed out
[2016-06-25 03:47:12] hk -1 (xxx.xxx.xxx.xxx:8080) timed out
[2016-06-25 03:47:12] hk -1 (xxx.xxx.xxx.xxx:8080) timed out
[2016-06-25 03:47:14] hk -1 (xxx.xxx.xxx.xxx:8080) timed out
[2016-06-25 03:47:14] hk -1 (xxx.xxx.xxx.xxx:8080) timed out
[2016-06-25 03:47:14] hk -1 (xxx.xxx.xxx.xxx:8080) timed out
[2016-06-25 03:47:15] hk -1 (xxx.xxx.xxx.xxx:8080) timed out
[2016-06-25 03:47:15] hk -1 (xxx.xxx.xxx.xxx:8080) timed out
[2016-06-25 03:47:15] System.Net.Sockets.SocketException (0x80004005): An invalid argument was supplied
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at Shadowsocks.Controller.Handler.StartConnect()

**Comment by chenshaoju** [comment]
你好，你换一个端口看看？

**Comment by liyiqqq** [comment]
是切换客户端代理的端口 还是vps的端口啊？
我也出现下面的问题，是一样的吗？

[2016-07-17 16:53:40] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.TCPHandler.StartConnect()

**Comment by chenshaoju** [comment]
＠liyiqqq 请尝试： https://github.com/shadowsocks/shadowsocks-windows/issues/591

**Comment by GangZhuo** [comment]
这一般是因为配置错误或者服务器不可用导致的。
