### ISSUE TITLE
shadowsocks cannot work on win10 14915

### ISSUE THREAD

**Issue by thune-xiaobai** [shadowsocks/shadowsocks-windows#731]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3 3.2 3.0(tested)

### Environment(Operating system, .NET Framework, etc)
win10 insider previre(14915.1000)   .net 4.6
server:debian8.5  Shadowsocks 2.8.2 
encryption method : aes-256-cfb

### Steps you have tried
resart,reconfigure nearly everything related.
works fine on my Android and linux

### Config and error log in detail (with all sensitive info masked)
on server
$:tail -f  /var/log/shadowsocks.log
2016-09-18 07:50:06 WARNING  unsupported addrtype 19, maybe wrong password or encryption method
2016-09-18 07:50:06 ERROR    can not parse header when handling connection from xxx.xxxxx.xxx:54575

shadowsocks-windows(version 3.3&&this only shows during the shadowsocks client was started):
[2016-09-18 15:46:30] Shadowsocks started
[2016-09-18 15:46:36] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by wongsyrone** [comment]
Double check your configuration. Your server denied connection.

> unsupported addrtype 19, maybe wrong password or encryption method

You can also try libev server

**Comment by thune-xiaobai** [comment]
I have checked several times
here is my local configuration:
    {
      "server": "xxx.xxx.xxx.xxx",
      "server_port": 6678,
      "password": "xxxxxxx",
      "method": "aes-256-cfb",
      "remarks": "",
      "auth": true
    },
and this is my server cmdline:
/usr/bin/python3 /usr/local/bin/ssserver -p 6678 -k xxxxxxxx -m aes-256-cfb --user root -d start

**Comment by wongsyrone** [comment]
try latest server: https://github.com/shadowsocks/shadowsocks/issues/622#issuecomment-247767011
