### ISSUE TITLE
shadowsocks3.3.3 exception 32 bit cannot access 64 bit module

### ISSUE THREAD

**Issue by luoyanghero** [shadowsocks/shadowsocks-windows#808]
I use shadowsocks2.3.1 old version, now update to 3.3.3. Before update, I have deleted:
C:\Users\Administrator\AppData\Local\Temp
ss_polipo.exe
shadowsocks.log
I have installed .Net 4.6.2

Shadowsocks3.3.3 environment:
Client system win7 64bit sp1

Exception Log:
[2016-10-20 12:50:57] System.ComponentModel.Win32Exception (0x80004005): A 32 bit processes cannot access modules of a 64 bit process.
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Shadowsocks.Controller.PrivoxyRunner.IsChildProcess(Process process)

Shadowsocks server verion:
Python version 2.8.2
CentOS 6.4 32bit

How should I do?
Should I update my server ss version? where can I get the install pakage?

**Comment by wongsyrone** [comment]
It seems you forgot to delete libsscrypto.dll

**Comment by luoyanghero** [comment]
Now I have deleted libsscrypto.dll. It still can not work, same exception log:
System.ComponentModel.Win32Exception (0x80004005): A 32 bit processes cannot access modules of a 64 bit process.

**Comment by luoyanghero** [comment]
Where can I get a tutor that how to install shadowsocks server in CentOS 6.x 64bit?

**Comment by wongsyrone** [comment]
Please try this debug version and post screenshot or logs if possible.

https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-0cn3i/build/1.0.105/job/t5yt8j9olkeqkeep/artifacts

**Comment by luoyanghero** [comment]
I use ss3.3.3 debug version, this is the log, I get the server log the same.
I tried old 2.3.1 version again, successful.

client log:
[2016-10-20 16:48:22] System.ComponentModel.Win32Exception (0x80004005): A 32 bit processes cannot access modules of a 64 bit process.
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Shadowsocks.Controller.PrivoxyRunner.IsChildProcess(Process process)
[2016-10-20 16:48:22] Shadowsocks started
[2016-10-20 16:48:25] Shadowsocks started
[2016-10-20 16:48:41] Socket connected to ss server: Do_1t (198.199.105.8:8388)
[2016-10-20 16:48:41] connect to www.youtube.com:443
[2016-10-20 16:48:42] Socket connected to ss server: Do_1t (198.199.105.8:8388)
[2016-10-20 16:48:42] connect to www.youtube.com:443
[2016-10-20 16:49:43] Socket connected to ss server: Do_1t (198.199.105.8:8388)
[2016-10-20 16:49:43] connect to www.youtube.com:443
[2016-10-20 16:49:43] Socket connected to ss server: Do_1t (198.199.105.8:8388)
[2016-10-20 16:49:43] connect to www.youtube.com:443
[2016-10-20 16:49:46] Socket connected to ss server: Do_1t (198.199.105.8:8388)
[2016-10-20 16:49:46] connect to clients2.google.com:443


ss server log(not the same time zone):
2016-10-20 08:49:22 WARNING  unsupported addrtype 19, maybe wrong password or encryption method
2016-10-20 08:49:22 ERROR    can not parse header when handling connection from 101.81.182.194:29774
2016-10-20 08:51:20 INFO     connecting www.youtube.com:443 from 101.81.182.194:3646
2016-10-20 08:51:27 WARNING  unsupported addrtype 19, maybe wrong password or encryption method
2016-10-20 08:51:27 ERROR    can not parse header when handling connection from 101.81.182.194:29785
2016-10-20 08:51:29 WARNING  unsupported addrtype 19, maybe wrong password or encryption method
2016-10-20 08:51:29 ERROR    can not parse header when handling connection from 101.81.182.194:29789
.....
2016-10-20 08:56:28 WARNING  unsupported addrtype 19, maybe wrong password or encryption method
2016-10-20 08:56:28 ERROR    can not parse header when handling connection from 101.81.182.194:29987
2016-10-20 08:56:43 WARNING  unsupported addrtype 19, maybe wrong password or encryption method
2016-10-20 08:56:43 ERROR    can not parse header when handling connection from 101.81.182.194:29991
2016-10-20 08:56:43 WARNING  unsupported addrtype 19, maybe wrong password or encryption method
2016-10-20 08:56:43 ERROR    can not parse header when handling connection from 101.81.182.194:29995
2016-10-20 08:56:54 WARNING  timed out: mtalk.google.com:5228
2016-10-20 08:56:54 INFO     connecting mtalk.google.com:5228 from 101.81.182.194:3570
2016-10-20 08:56:58 WARNING  unsupported addrtype 19, maybe wrong password or encryption method
2016-10-20 08:56:58 ERROR    can not parse header when handling connection from 101.81.182.194:29999
2016-10-20 08:56:59 WARNING  unsupported addrtype 19, maybe wrong password or encryption method
2016-10-20 08:56:59 ERROR    can not parse header when handling connection from 101.81.182.194:30003
2016-10-20 08:57:15 INFO     connecting sourceforge.net:443 from 101.81.182.194:29765
2016-10-20 08:57:17 INFO     connecting sourceforge.net:443 from 101.81.182.194:29769
2016-10-20 08:57:20 INFO     connecting clients4.google.com:443 from 101.81.182.194:3608
2016-10-20 08:57:21 INFO     connecting clients4.google.com:443 from 101.81.182.194:29773
2016-10-20 08:57:24 INFO     connecting www.youtube.com:443 from 101.81.182.194:29777
2016-10-20 08:57:27 INFO     connecting github.com:443 from 101.81.182.194:29784
2016-10-20 08:57:27 INFO     connecting github.com:443 from 101.81.182.194:29785
2016-10-20 08:57:28 INFO     connecting s.ytimg.com:443 from 101.81.182.194:29798

**Comment by luoyanghero** [comment]
I checked the encryption method, it's right.

**Comment by wongsyrone** [comment]
Do full temp folder cleanup or try portable mode.

**Comment by luoyanghero** [comment]
I always use portable mode by new a file named shadowsocks_portable_mode.txt.

**Comment by luoyanghero** [comment]
I reinstall ss server using GoVersion SS  not PathonVerion, it works. Thanks a lot.
By the way, how can I set auto start GoVer SS when reboot ?

**Comment by luoyanghero** [comment]
Now I use CentOS 7 64bit server system

**Comment by luoyanghero** [comment]
CentOS 6.x 32bit server system also OK when I use ss_go.
