### ISSUE TITLE
System.MissingMethodException wen connect to github.com:443

### ISSUE THREAD

**Issue by cxjava** [shadowsocks/shadowsocks-windows#815]
System.MissingMethodException when connect to github.com:443

### Version(release version or AppVeyor link)
Shadowsocks-3.3.4

### Environment(Operating system, .NET Framework, etc)
window 64  .NET version: 4.5.2

### Steps you have tried
I want to clone code from github through shadowsocks as proxy by git.

### What did you expect to see?
clone code successfully.

### What did you see instead?
when I downgrade to the version 3.3.3, clone code successfully!

### Config and error log in detail (with all sensitive info masked)

```
[2016-10-22 19:11:23] connect to api.github.com:443
[2016-10-22 19:11:23] System.MissingMethodException: Method not found: 'Void System.Security.Cryptography.RandomNumberGenerator.GetBytes(Byte[], Int32, Int32)'.
   at Shadowsocks.Encryption.IVEncryptor.randBytes(Byte[] buf, Int32 length)
   at Shadowsocks.Encryption.IVEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   at Shadowsocks.Controller.TCPHandler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2016-10-22 19:11:23] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

[2016-10-22 19:11:27] connect to github.com:443
[2016-10-22 19:11:27] System.MissingMethodException: Method not found: 'Void System.Security.Cryptography.RandomNumberGenerator.GetBytes(Byte[], Int32, Int32)'.
   at Shadowsocks.Encryption.IVEncryptor.randBytes(Byte[] buf, Int32 length)
   at Shadowsocks.Encryption.IVEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   at Shadowsocks.Controller.TCPHandler.PipeConnectionReceiveCallback(IAsyncResult ar)
```

**Comment by Yekaho** [comment]
github.com:443
Please confirm you fill the thing rightly....

**Comment by cxjava** [comment]
Yes, I am sure....

**Comment by wongsyrone** [comment]
Read release note.

**Comment by cxjava** [comment]
sorry for that... my carelessness!
