### ISSUE TITLE
win10-14959，Shadowsocks3.3.4非预期错误，Shadowsocks将退出。

### ISSUE THREAD

**Issue by searyts** [shadowsocks/shadowsocks-windows#868]
Exception Type: Exception

Stack Trace:

   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)

   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)

   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)

   at Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()

   at Shadowsocks.Controller.ShadowsocksController.ToggleEnable(Boolean enabled)

   at Shadowsocks.View.MenuViewController.EnableItem_Click(Object sender, EventArgs e)

   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)

   at System.Windows.Forms.MenuItem.MenuItemData.Execute()

   at System.Windows.Forms.Command.Invoke()

   at System.Windows.Forms.Command.DispatchID(Int32 id)

   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)

   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![shadowsocks](https://cloud.githubusercontent.com/assets/4506539/20088714/f8523e0e-a5bc-11e6-90df-7da76a50ce42.png)

**Comment by wongsyrone** [comment]
#864

**Comment by searyts** [comment]
@ @wongsyrone 对

**Comment by searyts** [comment]
@Noisyfox What's the matter, I don't know what the problem how to solve...

**Comment by Noisyfox** [comment]
We don't know either. We already got some open issues for this problem, no need to open another one.

**Comment by Noisyfox** [comment]
#814

**Comment by searyts** [comment]
@Noisyfox Well, thank you

**Comment by Noisyfox** [comment]
Try the latest pre-release version.
