### ISSUE TITLE
Non-UI Error

### ISSUE THREAD

**Issue by jonathonli** [shadowsocks/shadowsocks-windows#893]
### Version(release version or AppVeyor link)
Shadowsocks 3.0

### Environment(Operating system, .NET Framework, etc)
Windows 10 Pro Build 14965

### Config and error log in detail (with all sensitive info masked)
```
[2016-11-18 08:59:39] Shadowsocks started
[2016-11-18 09:09:27] Socket connected to ss server: JP 2016.5 (160.16.201.89:8437)
[2016-11-18 09:09:27] connect to tools.google.com:80
[2016-11-18 09:09:40] [E] System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Shadowsocks.Model.StatisticsRecord..ctor(String identifier, ICollection`1 inboundSpeedRecords, ICollection`1 outboundSpeedRecords, ICollection`1 latencyRecords)
   at Shadowsocks.Controller.AvailabilityStatistics.UpdateRecords()
   at Shadowsocks.Controller.AvailabilityStatistics.Run(Object _)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
```
![image](https://cloud.githubusercontent.com/assets/813491/20414910/fdbfb0a0-ad6f-11e6-83c1-dad00e4070c2.png)

**Comment by Noisyfox** [comment]
#890 
请暂时不要用统计功能
