### ISSUE TITLE
启动系统proxy会崩溃

### ISSUE THREAD

**Issue by Luckyboys** [shadowsocks/shadowsocks-windows#895]
![image](https://cloud.githubusercontent.com/assets/195125/20453465/76391da4-ae61-11e6-97df-f8748dc4d633.png)
![image](https://cloud.githubusercontent.com/assets/195125/20453487/1935f27a-ae62-11e6-9819-3621b8a4bb10.png)
3.3.3的时候没有这个情况

### Version(release version or AppVeyor link)
3.3.5

### Environment(Operating system, .NET Framework, etc)

.net framework 4.6.2已经安装

### Steps you have tried
发现删除gui-config.json会没问题，重新配置也没有问题，直到打开系统proxy，他自己就崩了

### What did you expect to see?
希望可以启用系统代理

### What did you see instead?
崩溃了

### Config and error log in detail (with all sensitive info masked)
```
[2016-11-19 10:35:31] Shadowsocks started
[2016-11-19 13:51:59] Shadowsocks started
[2016-11-19 13:56:57] Shadowsocks started
[2016-11-19 13:56:57] [E] System.Exception: InternetSetOption: 87
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   at Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   at Shadowsocks.Program.Main()
[2016-11-19 13:57:07] Shadowsocks started
[2016-11-19 13:57:07] [E] System.Exception: InternetSetOption: 87
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   at Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   at Shadowsocks.Program.Main()
[2016-11-19 13:57:58] Shadowsocks started
[2016-11-19 13:57:58] [E] System.Exception: InternetSetOption: 87
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   at Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   at Shadowsocks.Program.Main()
[2016-11-19 14:00:02] Shadowsocks started
[2016-11-19 14:00:02] [E] System.Exception: InternetSetOption: 87
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   at Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   at Shadowsocks.Program.Main()
[2016-11-19 14:00:31] Shadowsocks started
[2016-11-19 14:00:37] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:00:39] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:00:42] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:00:49] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:00:59] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:01:07] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:01:07] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:01:09] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:01:12] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:01:19] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:01:29] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:01:39] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:01:42] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:01:49] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:01:59] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:02:06] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:02:09] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:02:12] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:02:19] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:02:29] System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler..ctor(ShadowsocksController controller, Configuration config, TCPRelay tcprelay, Socket socket)
   at Shadowsocks.Controller.TCPRelay.Handle(Byte[] firstPacket, Int32 length, Socket socket, Object state)
   at Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-11-19 14:02:30] Shadowsocks started
[2016-11-19 14:02:49] Shadowsocks started
[2016-11-19 14:02:54] [E] Exception Type: Exception
Stack Trace:
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   at Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()
   at Shadowsocks.Controller.ShadowsocksController.ToggleEnable(Boolean enabled)
   at Shadowsocks.View.MenuViewController.EnableItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Command.DispatchID(Int32 id)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
[2016-11-19 14:03:04] [E] System.Exception: InternetSetOption: 87
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   at Shadowsocks.Controller.ShadowsocksController.Stop()
   at Shadowsocks.Program.Application_ApplicationExit(Object sender, EventArgs e)
   at System.Windows.Forms.Application.RaiseExit()
   at System.Windows.Forms.Application.ThreadContext.Dispose(Boolean postQuit)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run()
   at Shadowsocks.Program.Main()
[2016-11-19 14:03:17] Shadowsocks started
[2016-11-19 14:03:26] [E] Exception Type: Exception
Stack Trace:
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   at Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()
   at Shadowsocks.Controller.ShadowsocksController.ToggleEnable(Boolean enabled)
   at Shadowsocks.View.MenuViewController.EnableItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Command.DispatchID(Int32 id)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
[2016-11-19 14:03:27] [E] System.Exception: InternetSetOption: 87
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   at Shadowsocks.Controller.ShadowsocksController.Stop()
   at Shadowsocks.Program.Application_ApplicationExit(Object sender, EventArgs e)
   at System.Windows.Forms.Application.RaiseExit()
   at System.Windows.Forms.Application.ThreadContext.Dispose(Boolean postQuit)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run()
   at Shadowsocks.Program.Main()
[2016-11-19 14:03:50] Shadowsocks started
[2016-11-19 14:04:08] Detected: PAC file 'pac.txt' was changed.
[2016-11-19 14:06:24] Shadowsocks started
[2016-11-19 14:06:24] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:06:24] connect to mtalk.google.com:5228
[2016-11-19 14:06:25] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:06:25] connect to live.github.com:443
[2016-11-19 14:06:39] [E] Exception Type: Exception
Stack Trace:
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   at Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()
   at Shadowsocks.Controller.ShadowsocksController.ToggleEnable(Boolean enabled)
   at Shadowsocks.View.MenuViewController.EnableItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Command.DispatchID(Int32 id)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
[2016-11-19 14:06:42] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:06:42] connect to mail.google.com:443
[2016-11-19 14:07:14] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:07:14] connect to clients2.google.com:443
[2016-11-19 14:08:16] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:08:16] connect to www.google.com.hk:443
[2016-11-19 14:08:16] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:08:16] connect to www.google.com.hk:443
[2016-11-19 14:08:16] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:08:16] connect to www.google.com.hk:443
[2016-11-19 14:08:16] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:08:16] connect to www.google.com.hk:443
[2016-11-19 14:08:17] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:08:17] connect to ogs.google.com:443
[2016-11-19 14:08:22] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:08:22] connect to id.google.com.hk:443
[2016-11-19 14:08:22] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:08:22] connect to plus.google.com:443
[2016-11-19 14:08:22] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:08:22] connect to www.googleapis.com:443
[2016-11-19 14:08:25] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:08:25] connect to www.google.com:443
[2016-11-19 14:09:52] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:09:52] connect to clients4.google.com:443
[2016-11-19 14:10:02] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:10:02] connect to mtalk.google.com:5228
[2016-11-19 14:10:03] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:10:03] connect to live.github.com:443
[2016-11-19 14:10:12] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:10:12] connect to mail.google.com:443
[2016-11-19 14:10:14] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:10:14] connect to clients4.google.com:443
[2016-11-19 14:10:40] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:10:40] connect to ssl.gstatic.com:443
[2016-11-19 14:10:40] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:10:40] connect to docs.google.com:443
[2016-11-19 14:10:51] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:10:51] connect to clients4.google.com:443
[2016-11-19 14:11:33] [E] System.Exception: InternetSetOption: 87
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   at Shadowsocks.Controller.ShadowsocksController.Stop()
   at Shadowsocks.Program.Application_ApplicationExit(Object sender, EventArgs e)
   at System.Windows.Forms.Application.RaiseExit()
   at System.Windows.Forms.Application.ThreadContext.Dispose(Boolean postQuit)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run()
   at Shadowsocks.Program.Main()
[2016-11-19 14:12:49] Shadowsocks started
[2016-11-19 14:12:52] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:12:52] connect to api.github.com:443
[2016-11-19 14:12:56] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:12:56] connect to live.github.com:443
[2016-11-19 14:13:07] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:13:07] connect to www.google.com.hk:443
[2016-11-19 14:13:07] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:13:07] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:13:07] connect to www.google.com.hk:443
[2016-11-19 14:13:07] connect to www.google.com.hk:443
[2016-11-19 14:13:07] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:13:07] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:13:07] connect to www.google.com:443
[2016-11-19 14:13:07] connect to www.google.com:443
[2016-11-19 14:13:07] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:13:07] connect to www.google.com.hk:443
[2016-11-19 14:13:07] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:13:07] connect to www.google.com.hk:443
[2016-11-19 14:13:12] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:13:12] connect to mail.google.com:443
[2016-11-19 14:13:13] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:13:13] connect to clients4.google.com:443
[2016-11-19 14:14:01] Socket connected to ss server: YourDream (203.88.166.201:8666)
[2016-11-19 14:14:01] connect to mtalk.google.com:443
```

**Comment by wongsyrone** [comment]
Win10 预览版可以尝试https://github.com/shadowsocks/shadowsocks-windows/issues/814#issuecomment-261703070

**Comment by Noisyfox** [comment]
Try the latest pre-release version.
