### ISSUE TITLE
Always show timeout

### ISSUE THREAD

**Issue by suihonggang** [shadowsocks/shadowsocks-windows#908]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
Shadowsocks-3.3.5

### Environment(Operating system, .NET Framework, etc)
Win OS 10

### Steps you have tried
Open some webpage like google.com

### What did you see instead?
Fail to open google.com/gmail

[2016-11-26 19:34:26] 43.251.157.149:8388 timed out
[2016-11-26 19:34:27] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-11-26 19:35:35] 43.251.157.149:8388 timed out
[2016-11-26 19:35:38] 43.251.157.149:8388 timed out
[2016-11-26 19:35:40] 43.251.157.149:8388 timed out
[2016-11-26 19:35:43] 43.251.157.149:8388 timed out
[2016-11-26 19:35:45] 43.251.157.149:8388 timed out
[2016-11-26 19:35:48] 43.251.157.149:8388 timed out

### Config and error log in detail (with all sensitive info masked)

**Comment by lewjine** [comment]
try to change the "server_port" value to another or new port,eg:now server_port is 1234, try to set it 2345, then restart ssserver. It works for me for some time, but it maybe timeout out again after some.
In a word,  changing server_port to a new port when client log shows timeout.
