### ISSUE TITLE
Win10下启动崩溃

### ISSUE THREAD

**Issue by Cospotato** [shadowsocks/shadowsocks-windows#911]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
Shadowsocks 3.3.5(lastest release)

### Environment(Operating system, .NET Framework, etc)
Windows 10 Enterprise Insider Preview Build 14965.rs_prerelease.161104-1700

### Steps you have tried
Just start the application

### What did you expect to see?
A Exception Window says:
```
System.Exception: InternetSetOption: 87
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   at Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   at Shadowsocks.Program.Main()
```
### Full Log File
```
[2016-11-27 11:56:02] Shadowsocks started
[2016-11-27 11:56:02] [E] System.Exception: InternetSetOption: 87
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   at Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   at Shadowsocks.Program.Main()
[2016-11-27 11:56:09] kr2 (103.214.68.124:13038) timed out
[2016-11-27 11:56:09] HA switching to server: kr1 (103.214.68.123:13038)
[2016-11-27 11:56:10] Socket connected to ss server: kr1 (103.214.68.123:13038)
[2016-11-27 11:56:10] connect to api.github.com:443
[2016-11-27 11:56:11] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-11-27 11:56:23] HA switching to server: kr2 (103.214.68.124:13038)
[2016-11-27 11:56:23] Shadowsocks started
[2016-11-27 11:56:23] [E] System.Exception: InternetSetOption: 87
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL, String connName)
   at Shadowsocks.Util.SystemProxy.WinINet.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   at Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()
   at Shadowsocks.Controller.ShadowsocksController.Reload()
   at Shadowsocks.Program.Main()
```

**Comment by wongsyrone** [comment]
#814
