### ISSUE TITLE
Shadowsocks连接失败

### ISSUE THREAD

**Issue by zkailong** [shadowsocks/shadowsocks-windows#915]
Windows10 Pro Inside Preview 14971，2.5.2的SS，用了BandwagonHost的VPS，但是直连的话无法翻墙，用了Chrome+SwitchyOmega+SS之后能够正常翻墙。
手机端正常使用，可以确定配置文件没有问题。
迅雷是最新版，应该不是迅雷的问题。
请问这个应该怎么解决？

log:
[2016-11-29 21:24:16] Shadowsocks started
[2016-11-29 21:27:43] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2016-11-29 21:30:36] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2016-11-29 21:33:54] Shadowsocks started
[2016-11-29 21:38:03] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
看起来很像IP不对或者端口不对或者密码不对或者加密方式不对……

**Comment by Noisyfox** [comment]
关键是有个失败是PortForwarder，这个部分的链接的目标地址都是localhost不知道为啥还是出错了。看一下有没有开防火墙之类？或者是有别的服务占用了端口？

**Comment by wongsyrone** [comment]
> 2.5.2的SS

（揉揉眼

**Comment by zkailong** [comment]
@chenshaoju 我检查过了，都没有问题啊……而且真正奇怪的是，手机上是可以用的……

**Comment by zkailong** [comment]
@Noisyfox 防火墙我有允许SS的通过，应该不是防火墙的问题。端口的话……怎么看呢？

**Comment by zkailong** [comment]
@wongsyrone 第一次用Github……还不太会用……

**Comment by wongsyrone** [comment]
我的意思是为啥用那么古老的版本，不用新版呢

**Comment by zkailong** [comment]
@wongsyrone 我是直接在bandwagonhost上下载的，就是2.3的版本，刚才去下了最新版，还是不行……

**Comment by 772807886** [comment]
bandwagonhost上面会有这个软件的下载？？！

**Comment by zkailong** [comment]
@772807886 有啊……在控制台里面
