### ISSUE TITLE
Probleom

### ISSUE THREAD

**Issue by nerozjg** [shadowsocks/shadowsocks-windows#922]
[2016-12-05 08:41:29] System.IO.IOException: The process cannot access the file 'C:\WINDOWS\Temp\ss_privoxy.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   at Shadowsocks.Controller.PolipoRunner..cctor()

Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
Please try Portable mode,
Put a blank .txt file at shadowsocks.exe folder,and name it: shadowsocks_portable_mode.txt

**Comment by Noisyfox** [comment]
You are using a legacy version of SS, please update to the latest version.
